discovery:
  jobs:
    - type: alb
      regions:
        - eu-west-2
      enableMetricData: true
      delay: 120
      length: 60
      searchTags:
        - Key: Name
          Value: APP/DEV/FITNOTE.*
      metrics:
        - name: RequestCount
          delay: 120
          statistics:
            - Sum
          period: 60
          length: 60
        - name: HTTPCode_Target_2XX_Count
          delay: 120
          statistics:
            - Sum
          period: 60
          length: 60
          nilToZero: true
        - name: HTTPCode_Target_3XX_Count
          delay: 120
          statistics:
            - Sum
          period: 60
          length: 60
          nilToZero: true
        - name: HTTPCode_Target_4XX_Count
          delay: 120
          statistics:
            - Sum
          period: 60
          length: 60
          nilToZero: true
        - name: HTTPCode_Target_5XX_Count
          delay: 120
          statistics:
            - Sum
          period: 60
          length: 60
          nilToZero: true
    - type: sqs
      regions:
        - eu-west-2
      enableMetricData: true
      delay: 120
      length: 60
      searchTags:
        - Key: Name
          Value: NONPROD/FITNOTE/DEV/BLUE/DRS.*
      metrics:
        - name: NumberOfMessagesSent
          statistics:
            - Sum
          period: 60
          length: 60
          nilToZero: true
        - name: ApproximateAgeOfOldestMessage
          statistics:
            - Sum
          period: 60
          length: 60
          nilToZero: true
        - name: ApproximateNumberOfMessagesVisible
          statistics:
            - Sum
          period: 60
          length: 60
          nilToZero: true