#!/bin/bash

REPO_ROOT_DIR=$(git rev-parse --show-toplevel)
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
SINCE_COMMIT=$(diff -u <(git rev-list --first-parent "$CURRENT_BRANCH") <(git rev-list --first-parent main) | sed -ne 's/^ //p' | head -1)

docker run --rm -v "$REPO_ROOT_DIR:/app" trufflesecurity/trufflehog:3.14.0 git file:///app --only-verified --no-update --since-commit="$SINCE_COMMIT" --branch="$CURRENT_BRANCH" --fail