version: 2

updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "gitleaks"
        # For gitleaks, ignore all updates as new version then 1.6.0 are paid for
      
  - package-ecosystem: "docker"
    directory: "/docs"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "bundler"
    directory: "/docs"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "docker"
    directory: "/local"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "docker"
    directory: "/monitoring-as-code"
    schedule:
      interval: "weekly"

  - package-ecosystem: "bundler"
    directory: "/monitoring-as-code"
    schedule:
      interval: "weekly"   