version: 2

updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "docker"
    directory: "/docs"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "bundler"
    directory: "/docs"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "docker"
    directory: "/local"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "docker"
    directory: "/monitoring-as-code"
    schedule:
      interval: "weekly"     