version: 2

updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daliy"
      time: "07:00"
      timezone: "Europe/London"     
    ignore:
      - dependency-name: "gitleaks/gitleaks-action"
        # For gitleaks/gitleaks-action, ignore all updates as new version then 1.6.0 are paid for
      
  - package-ecosystem: "docker"
    directory: "/docs"
    schedule:
      interval: "daliy"
      time: "07:00"
      timezone: "Europe/London"

  - package-ecosystem: "bundler"
    directory: "/docs"
    schedule:
      interval: "daliy"
      time: "07:00"
      timezone: "Europe/London"
    
  - package-ecosystem: "docker"
    directory: "/monitoring-as-code"
    schedule:
      interval: "daliy"
      time: "07:00"
      timezone: "Europe/London"