{
 "title": "monitoring-product-view",
 "tags": [
  "monitoring",
  "mac-version: 68-builder-dockerfile-refinement",
  "product-view"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "environment", "label": "Environment", "query": "label_values(environment)" }
  ]
 },
 "panels": [
  { "title": "grafana", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SLI01 (7d)",
   "type": "stat",
   "description": "SLI01: requests to the Grafana landing page are successful",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((sli_value{service='monitoring', slo='SLI01', environment='$environment',\n          journey='grafana'}\n< bool 0.10000000000000001)[7d:1m]))\n/\nsum(sum_over_time((sli_value{service='monitoring', slo='SLI01', environment='$environment',\n          journey='grafana'}\n< bool Inf)[7d:1m]) > 0)\n",
     "legendFormat": "SLO Target 90.0 %"
    }
   ]
  },
  {
   "title": "SLI02 (7d)",
   "type": "stat",
   "description": "SLI02: requests to the Grafana login are successful",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((sli_value{service='monitoring', slo='SLI02', environment='$environment',\n          journey='grafana'}\n< bool 0.10000000000000001)[7d:1m]))\n/\nsum(sum_over_time((sli_value{service='monitoring', slo='SLI02', environment='$environment',\n          journey='grafana'}\n< bool Inf)[7d:1m]) > 0)\n",
     "legendFormat": "SLO Target 90.0 %"
    }
   ]
  },
  {
   "title": "SLI03 (7d)",
   "type": "stat",
   "description": "SLI03: requests to the Grafana datasources are successful",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((sli_value{service='monitoring', slo='SLI03', environment='$environment',\n          journey='grafana'}\n< bool 0.5)[7d:1m]))\n/\nsum(sum_over_time((sli_value{service='monitoring', slo='SLI03', environment='$environment',\n          journey='grafana'}\n< bool Inf)[7d:1m]) > 0)\n",
     "legendFormat": "SLO Target 90.0 %"
    }
   ]
  },
  { "title": "prometheus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "SLI01 (7d)",
   "type": "stat",
   "description": "SLI01: all prometheus scrape targets are available",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((sli_value{service='monitoring', slo='SLI01', environment='$environment',\n          journey='prometheus'}\n== bool 1)[7d:1m]))\n/\nsum(sum_over_time((sli_value{service='monitoring', slo='SLI01', environment='$environment',\n          journey='prometheus'}\n< bool Inf)[7d:1m]) > 0)\n",
     "legendFormat": "SLO Target 90.0 %"
    }
   ]
  },
  {
   "title": "SLI02 (7d)",
   "type": "stat",
   "description": "SLI02: prometheus scraping of Yace is fast enough",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((sli_value{service='monitoring', slo='SLI02', environment='$environment',\n          journey='prometheus'}\n< bool 15)[7d:1m]))\n/\nsum(sum_over_time((sli_value{service='monitoring', slo='SLI02', environment='$environment',\n          journey='prometheus'}\n< bool Inf)[7d:1m]) > 0)\n",
     "legendFormat": "SLO Target 90.0 %"
    }
   ]
  },
  { "title": "thanos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "SLI01 (7d)",
   "type": "stat",
   "description": "SLI01: instant query requests to Thanos",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((sli_value{service='monitoring', slo='SLI01', environment='$environment',\n          journey='thanos'}\n< bool 0.10000000000000001)[7d:1m]))\n/\nsum(sum_over_time((sli_value{service='monitoring', slo='SLI01', environment='$environment',\n          journey='thanos'}\n< bool Inf)[7d:1m]) > 0)\n",
     "legendFormat": "SLO Target 90.0 %"
    }
   ]
  },
  {
   "title": "SLI02 (7d)",
   "type": "stat",
   "description": "SLI02: instant query requests to Thanos are fast enough",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((sli_value{service='monitoring', slo='SLI02', environment='$environment',\n          journey='thanos'}\n< bool 15)[7d:1m]))\n/\nsum(sum_over_time((sli_value{service='monitoring', slo='SLI02', environment='$environment',\n          journey='thanos'}\n< bool Inf)[7d:1m]) > 0)\n",
     "legendFormat": "SLO Target 90.0 %"
    }
   ]
  },
  {
   "title": "SLI03 (7d)",
   "type": "stat",
   "description": "SLI03: range query requests to Thanos",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((sli_value{service='monitoring', slo='SLI03', environment='$environment',\n          journey='thanos'}\n< bool 0.10000000000000001)[7d:1m]))\n/\nsum(sum_over_time((sli_value{service='monitoring', slo='SLI03', environment='$environment',\n          journey='thanos'}\n< bool Inf)[7d:1m]) > 0)\n",
     "legendFormat": "SLO Target 90.0 %"
    }
   ]
  },
  {
   "title": "SLI04 (7d)",
   "type": "stat",
   "description": "SLI04: range query requests to Thanos are fast enough",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((sli_value{service='monitoring', slo='SLI04', environment='$environment',\n          journey='thanos'}\n< bool 10)[7d:1m]))\n/\nsum(sum_over_time((sli_value{service='monitoring', slo='SLI04', environment='$environment',\n          journey='thanos'}\n< bool Inf)[7d:1m]) > 0)\n",
     "legendFormat": "SLO Target 90.0 %"
    }
   ]
  },
  {
   "title": "SLI05 (7d)",
   "type": "stat",
   "description": "SLI05: compactions by thanos-compact",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((sli_value{service='monitoring', slo='SLI05', environment='$environment',\n          journey='thanos'}\n< bool 0.01)[7d:1m]))\n/\nsum(sum_over_time((sli_value{service='monitoring', slo='SLI05', environment='$environment',\n          journey='thanos'}\n< bool Inf)[7d:1m]) > 0)\n",
     "legendFormat": "SLO Target 99.0 %"
    }
   ]
  }
 ]
}