# Values for jenkins.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.

controller:
  # Used for label app.kubernetes.io/component
  componentName: "jenkins-controller"
  image: "jenkins/jenkins"
  tag: "2.289.2-jdk11"
  imagePullPolicy: "IfNotPresent"

  podSecurityContextOverride:
    runAsUser: 0
    fsGroup: 0

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hostName: jenkins.home.local

  # List of plugins to be install during Jenkins controller start.
  installPlugins:
    - kubernetes:1.30.1
    - workflow-aggregator:2.6
    - git:4.7.2
    - configuration-as-code:1.51
    - ace-editor:1.1
    - antisamy-markup-formatter:2.1
    - apache-httpcomponents-client-4-api:4.5.13-1.0
    - authentication-tokens:1.4
    - bootstrap4-api:4.6.0-3
    - bootstrap5-api:5.0.2-1
    - bouncycastle-api:2.21
    - branch-api:2.6.5
    - caffeine-api:2.9.1-23.v51c4e2c879c8
    - checks-api:1.7.2
    - cloudbees-folder:6.15
    - command-launcher:1.6
    - credentials-binding:1.27
    - credentials:2.5
    - display-url-api:2.3.5
    - docker-commons:1.17
    - docker-workflow:1.26
    - durable-task:1.38
    - echarts-api:5.1.2-3
    - font-awesome-api:5.15.3-4
    - git-client:3.8.0
    - git-server:1.10
    - handlebars:3.0.8
    - icon-shim:3.0.0
    - jackson2-api:2.12.4
    - jaxb:2.3.0.1
    - jdk-tool:1.5
    - jquery-detached:1.2.1
    - jquery3-api:3.6.0-2
    - jsch:0.1.55.2
    - junit:1.51
    - kubernetes-client-api:5.4.1
    - lockable-resources:2.11
    - mailer:1.34
    - matrix-auth:2.6.8
    - matrix-project:1.19
    - metrics:4.0.2.8
    - momentjs:1.1.1
    - pipeline-build-step:2.14
    - pipeline-graph-analysis:1.11
    - pipeline-input-step:2.12
    - pipeline-milestone-step:1.3.2
    - pipeline-model-api:1.8.5
    - pipeline-model-declarative-agent:1.1.1
    - pipeline-model-definition:1.8.5
    - pipeline-model-extensions:1.8.5
    - pipeline-rest-api:2.19
    - pipeline-stage-step:2.5
    - pipeline-stage-tags-metadata:1.8.5
    - pipeline-stage-view:2.19
    - plain-credentials:1.7
    - plugin-util-api:2.4.0
    - popper-api:1.16.1-2
    - popper2-api:2.5.4-3
    - scm-api:2.6.4
    - script-security:1.77
    - snakeyaml-api:1.29.1
    - ssh-credentials:1.19
    - sshd:3.1.0
    - structs:1.23
    - trilead-api:1.0.13
    - variant:1.4
    - windows-slaves:1.8
    - workflow-api:2.46
    - workflow-basic-steps:2.23
    - workflow-cps-global-lib:2.21
    - workflow-cps:2.93
    - workflow-durable-task-step:2.39
    - workflow-job:2.41
    - workflow-multibranch:2.26
    - workflow-scm-step:2.13
    - workflow-step-api:2.24
    - workflow-support:3.8

persistence:
  enabled: true
  ## A manually managed Persistent Volume and Claim
  ## Requires persistence.enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  existingClaim: jenkins-pvc
  
serviceAccount:
  create: false
  # The name of the service account
  name: jenkins
  

  