{
 "title": "flapi-writeback-journey-view",
 "tags": [
  "flapi",
  "writeback",
  "journey-view"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "error_budget_span", "label": "Error Budget Display", "query": "10m,1h,1d,7d,21d,30d,90d" },
   { "name": "environment", "label": "Environment", "query": "label_values(environment)" }
  ]
 },
 "panels": [
  {
   "title": "SLI01: Percentage of time Availability - FLAPI Create Case",
   "type": "row"
  },
  {
   "title": "SLO Performance (7d)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(slo_ok{service='flapi',slo='SLI01',environment='$environment',journey='writeback'}[7d])) / sum(sum_over_time(slo_sample{service='flapi',slo='SLI01',environment='$environment',journey='writeback'}[7d]) > 0)",
     "legendFormat": "SLO Target 90%"
    }
   ]
  },
  {
   "title": "Error budget remaining over previous 7d",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(0.10000000000000001 - (1 - (sum(sum_over_time( slo_ok{service='flapi',slo='SLI01',environment='$environment',journey='writeback'}[7d] ))  / sum(sum_over_time(slo_sample{service='flapi',slo='SLI01',environment='$environment',journey='writeback'}[7d]) ) ) ) ) / 0.10000000000000001",
     "legendFormat": "Remaining Error Budget"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 0.5, "x": 14, "y": 0 } },
  {
   "type": "graph",
   "description": "Error rate for Availability - FLAPI Create Case should be below 10.0%",
   "gridPos": { "h": 1, "w": 9, "x": 14.5, "y": 0 },
   "targets": [
    {
     "expr": "sum_over_time ( slo_ok { service='flapi',slo='SLI01',environment='$environment',journey='writeback' } [ $__interval ] )\n/ \nsum_over_time ( slo_sample { service='flapi',slo='SLI01',environment='$environment',journey='writeback' } [ $__interval ] )\n",
     "legendFormat": "SLO OK"
    },
    {
     "expr": "1 - (\n  sum_over_time ( slo_ok { service='flapi',slo='SLI01',environment='$environment',journey='writeback' } [ $__interval ] )\n  / \n  sum_over_time ( slo_sample { service='flapi',slo='SLI01',environment='$environment',journey='writeback' } [ $__interval ] )\n)\n",
     "legendFormat": "SLO Fail"
    }
   ]
  },
  {
   "title": "Requests, errors, and error rate - Availability - FLAPI Create Case",
   "type": "graph",
   "description": "* Sample interval is 5m \n* Request selectors are job=\\~\".*/fetm-flapi-wb\" \n* Error selectors are status=\\~\"4..|5..\"\n",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=~\".*/fetm-flapi-wb\",host=\"$environment\"}[5m]) or vector(0))",
     "legendFormat": "Requests per second"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=~\".*/fetm-flapi-wb\",host=\"$environment\",status=~\"4..|5..\"}[5m]) or vector(0))",
     "legendFormat": "Errors per second"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=~\".*/fetm-flapi-wb\",host=\"$environment\",status=~\"4..|5..\"}[5m]) or vector(0)) / sum(rate(http_server_requests_seconds_count{job=~\".*/fetm-flapi-wb\",host=\"$environment\"}[5m]) or vector(0))",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "SLI02: Percentage of time Latency - FLAPI Create Case",
   "type": "row"
  },
  {
   "title": "SLO Performance (7d)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(slo_ok{service='flapi',slo='SLI02',environment='$environment',journey='writeback'}[7d])) / sum(sum_over_time(slo_sample{service='flapi',slo='SLI02',environment='$environment',journey='writeback'}[7d]) > 0)",
     "legendFormat": "SLO Target 90%"
    }
   ]
  },
  {
   "title": "Error budget remaining over previous 7d",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(0.10000000000000001 - (1 - (sum(sum_over_time( slo_ok{service='flapi',slo='SLI02',environment='$environment',journey='writeback'}[7d] ))  / sum(sum_over_time(slo_sample{service='flapi',slo='SLI02',environment='$environment',journey='writeback'}[7d]) ) ) ) ) / 0.10000000000000001",
     "legendFormat": "Remaining Error Budget"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 0.5, "x": 14, "y": 0 } },
  {
   "type": "graph",
   "description": "Request latency for Latency - FLAPI Create Case should be below 0.8s for the 95th percentile",
   "gridPos": { "h": 1, "w": 9, "x": 14.5, "y": 0 },
   "targets": [
    {
     "expr": "sum_over_time ( slo_ok { service='flapi',slo='SLI02',environment='$environment',journey='writeback' } [ $__interval ] )\n/ \nsum_over_time ( slo_sample { service='flapi',slo='SLI02',environment='$environment',journey='writeback' } [ $__interval ] )\n",
     "legendFormat": "SLO OK"
    },
    {
     "expr": "1 - (\n  sum_over_time ( slo_ok { service='flapi',slo='SLI02',environment='$environment',journey='writeback' } [ $__interval ] )\n  / \n  sum_over_time ( slo_sample { service='flapi',slo='SLI02',environment='$environment',journey='writeback' } [ $__interval ] )\n)\n",
     "legendFormat": "SLO Fail"
    }
   ]
  },
  {
   "title": "Latency - Latency - FLAPI Create Case",
   "type": "graph",
   "description": "* Sample interval is 5m \n* Request selectors are job=\\~\".*/fetm-flapi-wb\" \n",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{job=~\".*/fetm-flapi-wb\",host=\"$environment\"}[5m]) or vector(0)) /  sum(rate(http_server_requests_seconds_count{job=~\".*/fetm-flapi-wb\",host=\"$environment\"}[5m]) or vector(0))",
     "legendFormat": "Average Latency"
    }
   ]
  }
 ]
}