{
 "title": "flapi-detail-view",
 "tags": [
  "flapi",
  "detail",
  "promclient"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "inbound_path", "label": "Inbound Request Path", "query": "label_values(uri)" },
   { "name": "outbound_path", "label": "Outbound Request Path", "query": "label_values(uri)" },
   { "name": "inbound_response_code", "label": "Inbound Request Response Code", "query": "label_values(status)" },
   { "name": "outbound_response_code", "label": "Outbound Request Response Code", "query": "label_values(status)" },
   { "name": "environment", "label": "Environment", "query": "label_values(environment)" },
   { "name": "latency_percentile", "label": "Latency Percentile", "query": "50,80,90,95,99" }
  ]
 },
 "panels": [
  { "title": "Inbound HTTP Requests", "type": "row", "gridPos": { "h": 1, "w": 24 } },
  {
   "title": "Availability - requests per second by response code",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(http_server_requests_seconds_count{job=\"localhost/fetm-flapi-wb\", host=~\"$environment\",uri=~\"$inbound_path\",status=~\"$inbound_response_code\"}[$__rate_interval]))",
     "legendFormat": "{{inbound_response_code}}"
    }
   ]
  },
  {
   "title": "Availability - requests per second by path",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_count{job=\"localhost/fetm-flapi-wb\", host=~\"$environment\",uri=~\"$inbound_path\",status=~\"$inbound_response_code\"}[$__rate_interval]))",
     "legendFormat": "{{inbound_path}}"
    }
   ]
  },
  {
   "title": "Latency - heatmap for request latency",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12 },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_bucket{job=\"localhost/fetm-flapi-wb\", host=~\"$environment\",uri=~\"$inbound_path\",status=~\"$inbound_response_code\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Latency - requests per selected latency percentile",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($latency_percentile/100, (sum (rate(http_server_requests_seconds_bucket{job=\"localhost/fetm-flapi-wb\",host=~\"$environment\",uri=~\"$inbound_path\",status=~\"$inbound_response_code\"}[$__rate_interval])) by (le)))",
     "legendFormat": "Selected Percentile Latency"
    }
   ]
  },
  { "title": "Outbound HTTP Requests", "type": "row", "gridPos": { "h": 1, "w": 24 } },
  {
   "title": "Availability - requests per second by response code",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(http_client_requests_seconds_count{job=\"localhost/fetm-flapi-wb\", host=~\"$environment\",uri=~\"$outbound_path\",status=~\"$outbound_response_code\"}[$__rate_interval]))",
     "legendFormat": "{{outbound_response_code}}"
    }
   ]
  },
  {
   "title": "Availability - requests per second by path",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_client_requests_seconds_count{job=\"localhost/fetm-flapi-wb\", host=~\"$environment\",uri=~\"$outbound_path\",status=~\"$outbound_response_code\"}[$__rate_interval]))",
     "legendFormat": "{{outbound_path}}"
    }
   ]
  },
  {
   "title": "Latency - heatmap for request latency",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12 },
   "targets": [
    {
     "expr": "sum(increase(http_client_requests_seconds_bucket{job=\"localhost/fetm-flapi-wb\", host=~\"$environment\",uri=~\"$outbound_path\",status=~\"$outbound_response_code\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Latency - requests per selected latency percentile",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($latency_percentile/100, (sum (rate(http_client_requests_seconds_bucket{job=\"localhost/fetm-flapi-wb\",host=~\"$environment\",uri=~\"$outbound_path\",status=~\"$outbound_response_code\"}[$__rate_interval])) by (le)))",
     "legendFormat": "Selected Percentile Latency"
    }
   ]
  }
 ]
}