# The root route on which each incoming alert enters.
route:
    receiver: specified-slackchannel
    # The labels by which incoming alerts are grouped together. For example,
    # multiple alerts coming in for cluster=A and alertname=LatencyHigh would
    # be batched into a single group.
    group_by: ['alertname', 'environment', 'service', 'journey']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 1h
    matchers:
        - severity != test

# A list of notification receivers.
receivers:
    - name: specified-slackchannel
      slack_configs:
      - send_resolved: true
        api_url: '@@AM_SLACK_API_URL@@'
        channel: '#{{ or .CommonLabels.label_monitoring_slackchannel .CommonLabels.monitoring_slackchannel
          }}'
        username: '{{ template "slack.default.username" . }}'
        color: '{{ template "slack.color" . }}'
        title: '{{ template "slack.title" . }}'
        title_link: '{{ template "slack.default.titlelink" . }}'
        pretext: '{{ template "slack.default.pretext" . }}'
        text: '{{ template "slack.text" . }}'
        footer: '{{ template "slack.default.footer" . }}'
        fallback: '{{ template "slack.default.fallback" . }}'
        callback_id: '{{ template "slack.default.callbackid" . }}'
        icon_emoji: '{{ template "slack.default.iconemoji" . }}'
        icon_url: '{{ template "slack.default.iconurl" . }}'
        actions:
        - type: button
          text: 'Runbook :green_book:'
          url: '{{ (index .Alerts 0).Annotations.runbook_url }}'
        - type: button
          text: 'Query :mag:'
          url: '{{ (index .Alerts 0).GeneratorURL }}'
        - type: button
          text: 'Dashboard :desktop_computer:'
          url: '{{ (index .Alerts 0).Annotations.dashboard }}'
        - type: button
          text: 'Silence :no_bell:'
          url: '{{ template "__alert_silence_link" . }}'
        - type: button
          text: '{{ template "slack.link_button_text" . }}'
          url: '{{ .CommonAnnotations.link_url }}'

templates:
- /etc/alertmanager/platform-e-templates.tmpl