# Auto-discovery configuration
discovery:
  exportedTagsOnMetrics:
    # List of tags per service to export to all metrics
    sqs:
      - Team
      - CreatedBy
      - Environment
    es:
      - Team
      - CreatedBy
      - Environment
    rds:
      - Team
      - CreatedBy
      - Environment
  # List of auto-discovery jobs
  jobs:
    # AWS ALB Service CloudWatch Namespace
    - type: sqs
      # AWS Region
      regions:
        - eu-west-2
      # Export the metric with original cloudwatch timestamp
      addCloudwatchTimestamp: true
      # If set it will request metrics up until current_time - delay
      delay: 120
      # How far back to request data for in seconds
      length: 120
      # AWS resource tag filtering
      searchTags:
        - key: Environment
          value: '@@YACE_ENVIRONMENT_TAG@@'
      # List of metric definitions
      metrics:
        # CloudWatch metric name
        - name: ApproximateNumberOfMessagesVisible
          # List of statistic types, e.g. "Minimum", "Maximum", etc.
          statistics:
            - Sum
          # Statistic period in seconds (Overrides job level setting)
          period: 60
          # How far back to request data for in seconds
          length: 120
          # Return 0 value if Cloudwatch returns no metrics at all
          nilToZero: true
        - name: NumberOfMessagesDeleted
          statistics:
            - Sum
          period: 60
          length: 120
          nilToZero: true
        - name: ApproximateAgeOfOldestMessage
          statistics:
            - Sum
          period: 60
          length: 120
          nilToZero: true
        - name: NumberOfMessagesSent
          statistics:
            - Sum
          period: 60
          length: 120
          nilToZero: true
    - type: es
      regions:
        - eu-west-2
      addCloudwatchTimestamp: true
      delay: 120
      length: 120
      searchTags:
        - key: Environment
          value: '@@YACE_ENVIRONMENT_TAG@@'
      metrics:
        - name: SearchLatency
          statistics:
            - Sum
          period: 60
          length: 120
          nilToZero: true
      metrics:
        - name: SearchRate
          statistics:
            - Sum
          period: 60
          length: 120
          nilToZero: true
      metrics:
        - name: 2xx
          statistics:
            - Sum
          period: 60
          length: 120
          nilToZero: true
      metrics:
        - name: 3xx
          statistics:
            - Sum
          period: 60
          length: 120
          nilToZero: true
      metrics:
        - name: 4xx
          statistics:
            - Sum
          period: 60
          length: 120
          nilToZero: true
      metrics:
        - name: 5xx
          statistics:
            - Sum
          period: 60
          length: 120
          nilToZero: true
    - type: rds
      regions:
        - eu-west-2
      addCloudwatchTimestamp: true
      delay: 120
      length: 120
      searchTags:
        - key: Environment
          value: '@@YACE_ENVIRONMENT_TAG@@'
      metrics:
        - name: ReadLatency
          statistics:
            - Average
          period: 60
          length: 120
          nilToZero: true
      metrics:
        - name: ReadThroughput
          statistics:
            - Average
          period: 60
          length: 120
          nilToZero: true
      metrics:
        - name: ReadIOPS
          statistics:
            - Average
          period: 60
          length: 120
          nilToZero: true
      metrics:
        - name: WriteLatency
          statistics:
            - Average
          period: 60
          length: 120
          nilToZero: true
      metrics:
        - name: WriteThroughput
          statistics:
            - Average
          period: 60
          length: 120
          nilToZero: true
      metrics:
        - name: WriteIOPS
          statistics:
            - Average
          period: 60
          length: 120
          nilToZero: true