name: Feature request
description: Request a new feature or enhancement
title: "[Feature Request]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    id: title
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request.
        
  - type: checkboxes
    id: terms
    attributes:
      label: Before submitting
      description: I have already searched the [existing issues](https://github.com/HO-CTO/sre-monitoring-as-code/issues) and cannot find another that matches this one.
      options:
        - label: I agree
          required: true
          
  - type: textarea
    id: describe
    attributes:
      label: Describe the user need
      description: A clear and concise description of the requirement.
      placeholder: Describe the user need.
    validations:
      required: true

  - type: textarea
    id: possible-solutions
    attributes:
      label: Describe the solution you would like
      description: A clear and concise description of the solution you would like.
      placeholder: |
        Describe the desired solution.
    validations:
      required: true

  - type: textarea
    id: other
    attributes:
      label: Any other information
      description: Any other information or additional context you would like to provide.