{
 "title": "monitoring-grafana-journey-view",
 "tags": [
  "monitoring",
  "mac-version: local",
  "grafana",
  "journey-view"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "error_budget_span", "label": "Error Budget Display", "query": "10m,1h,1d,7d,21d,30d,90d" },
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(sli_value{service=\"monitoring\"}, sli_environment)"
   }
  ]
 },
 "panels": [
  {
   "title": "SLI01: requests to the Grafana landing page are successful",
   "type": "row"
  },
  {
   "title": " Availability (7d)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI01\", journey=\"grafana\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"}\n< bool 0.10000000000000001)[7d:1m]))\n/\nsum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI01\", journey=\"grafana\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"}\n< bool Inf)[7d:1m]) > 0)\n",
     "legendFormat": "SLO Target 90.0 %"
    }
   ]
  },
  {
   "title": "Error budget remaining over previous 7d",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(0.10000000000000001 - (1 - (sum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI01\", journey=\"grafana\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"}\n< bool 0.10000000000000001)[7d:1m]))\n/\nsum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI01\", journey=\"grafana\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"}\n< bool Inf)[7d:1m])))))\n/\n0.10000000000000001\n",
     "legendFormat": "Remaining Error Budget"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 0.5, "x": 14, "y": 0 } },
  {
   "type": "graph",
   "description": "Error rate for Grafana landing page requests should be below 10.0%",
   "gridPos": { "h": 1, "w": 9, "x": 14.5, "y": 0 },
   "targets": [
    {
     "expr": "sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI01\", journey=\"grafana\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} < bool 0.10000000000000001)[$__interval:1m])\n/ \nsum_over_time((sli_value{service=\"monitoring\", sli=\"SLI01\", journey=\"grafana\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} < bool Inf)[$__interval:1m])\n",
     "legendFormat": "SLO OK"
    },
    {
     "expr": "1 - (\n  sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI01\", journey=\"grafana\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} < bool 0.10000000000000001)[$__interval:1m])\n  / \n  sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI01\", journey=\"grafana\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} < bool Inf)[$__interval:1m])\n)\n",
     "legendFormat": "SLO Fail"
    }
   ]
  },
  {
   "title": "Grafana landing page requests",
   "type": "graph",
   "description": "* Sample interval is 1m\n* Selectors are job=\\~\"grafana\", handler=\\~\"/api/dashboards/home\"\n* Error selectors are status_code=~\"4..|5..\"\n",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grafana_http_request_duration_seconds_count{job=~\"grafana\",handler=~\"/api/dashboards/home\",namespace=~\"$environment\"}[1m]))\n",
     "legendFormat": "requests per second"
    },
    {
     "expr": "sum(rate(grafana_http_request_duration_seconds_count{job=~\"grafana\",handler=~\"/api/dashboards/home\",namespace=~\"$environment\", status_code=~\"4..|5..\"}[1m]) or vector(0))\n",
     "legendFormat": "errors per second"
    },
    {
     "expr": "sum(rate(grafana_http_request_duration_seconds_count{job=~\"grafana\",handler=~\"/api/dashboards/home\",namespace=~\"$environment\", status_code=~\"4..|5..\"}[1m]) or vector(0))\n/\nsum(rate(grafana_http_request_duration_seconds_count{job=~\"grafana\",handler=~\"/api/dashboards/home\",namespace=~\"$environment\"}[1m]))\n",
     "legendFormat": "error rate"
    }
   ]
  },
  {
   "title": "SLI02: requests to the Grafana login are successful",
   "type": "row"
  },
  {
   "title": " Availability (7d)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI02\", journey=\"grafana\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"}\n< bool 0.10000000000000001)[7d:1m]))\n/\nsum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI02\", journey=\"grafana\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"}\n< bool Inf)[7d:1m]) > 0)\n",
     "legendFormat": "SLO Target 90.0 %"
    }
   ]
  },
  {
   "title": "Error budget remaining over previous 7d",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(0.10000000000000001 - (1 - (sum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI02\", journey=\"grafana\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"}\n< bool 0.10000000000000001)[7d:1m]))\n/\nsum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI02\", journey=\"grafana\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"}\n< bool Inf)[7d:1m])))))\n/\n0.10000000000000001\n",
     "legendFormat": "Remaining Error Budget"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 0.5, "x": 14, "y": 0 } },
  {
   "type": "graph",
   "description": "Error rate for Grafana login page requests should be below 10.0%",
   "gridPos": { "h": 1, "w": 9, "x": 14.5, "y": 0 },
   "targets": [
    {
     "expr": "sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI02\", journey=\"grafana\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} < bool 0.10000000000000001)[$__interval:1m])\n/ \nsum_over_time((sli_value{service=\"monitoring\", sli=\"SLI02\", journey=\"grafana\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} < bool Inf)[$__interval:1m])\n",
     "legendFormat": "SLO OK"
    },
    {
     "expr": "1 - (\n  sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI02\", journey=\"grafana\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} < bool 0.10000000000000001)[$__interval:1m])\n  / \n  sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI02\", journey=\"grafana\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} < bool Inf)[$__interval:1m])\n)\n",
     "legendFormat": "SLO Fail"
    }
   ]
  },
  {
   "title": "Grafana login page requests",
   "type": "graph",
   "description": "* Sample interval is 1m\n* Selectors are job=\\~\"grafana\", handler=\\~\"/login\"\n* Error selectors are status_code=~\"4..|5..\"\n",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grafana_http_request_duration_seconds_count{job=~\"grafana\",handler=~\"/login\",namespace=~\"$environment\"}[1m]))\n",
     "legendFormat": "requests per second"
    },
    {
     "expr": "sum(rate(grafana_http_request_duration_seconds_count{job=~\"grafana\",handler=~\"/login\",namespace=~\"$environment\", status_code=~\"4..|5..\"}[1m]) or vector(0))\n",
     "legendFormat": "errors per second"
    },
    {
     "expr": "sum(rate(grafana_http_request_duration_seconds_count{job=~\"grafana\",handler=~\"/login\",namespace=~\"$environment\", status_code=~\"4..|5..\"}[1m]) or vector(0))\n/\nsum(rate(grafana_http_request_duration_seconds_count{job=~\"grafana\",handler=~\"/login\",namespace=~\"$environment\"}[1m]))\n",
     "legendFormat": "error rate"
    }
   ]
  },
  {
   "title": "SLI03: requests to the Grafana datasources are successful",
   "type": "row"
  },
  {
   "title": " Availability (7d)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI03\", journey=\"grafana\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"}\n< bool 0.5)[7d:1m]))\n/\nsum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI03\", journey=\"grafana\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"}\n< bool Inf)[7d:1m]) > 0)\n",
     "legendFormat": "SLO Target 90.0 %"
    }
   ]
  },
  {
   "title": "Error budget remaining over previous 7d",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(0.10000000000000001 - (1 - (sum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI03\", journey=\"grafana\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"}\n< bool 0.5)[7d:1m]))\n/\nsum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI03\", journey=\"grafana\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"}\n< bool Inf)[7d:1m])))))\n/\n0.10000000000000001\n",
     "legendFormat": "Remaining Error Budget"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 0.5, "x": 14, "y": 0 } },
  {
   "type": "graph",
   "description": "Error rate for Grafana  datasource API requests should be below 50.0%",
   "gridPos": { "h": 1, "w": 9, "x": 14.5, "y": 0 },
   "targets": [
    {
     "expr": "sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI03\", journey=\"grafana\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} < bool 0.5)[$__interval:1m])\n/ \nsum_over_time((sli_value{service=\"monitoring\", sli=\"SLI03\", journey=\"grafana\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} < bool Inf)[$__interval:1m])\n",
     "legendFormat": "SLO OK"
    },
    {
     "expr": "1 - (\n  sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI03\", journey=\"grafana\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} < bool 0.5)[$__interval:1m])\n  / \n  sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI03\", journey=\"grafana\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} < bool Inf)[$__interval:1m])\n)\n",
     "legendFormat": "SLO Fail"
    }
   ]
  },
  {
   "title": "Grafana  datasource API requests",
   "type": "graph",
   "description": "* Sample interval is 1m\n* Selectors are job=\\~\"grafana\", handler=\\~\"/api/datasources/proxy/:id/.*\"\n* Error selectors are status_code=~\"4..|5..\"\n",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grafana_http_request_duration_seconds_count{job=~\"grafana\",handler=~\"/api/datasources/proxy/:id/.*\",namespace=~\"$environment\"}[1m]))\n",
     "legendFormat": "requests per second"
    },
    {
     "expr": "sum(rate(grafana_http_request_duration_seconds_count{job=~\"grafana\",handler=~\"/api/datasources/proxy/:id/.*\",namespace=~\"$environment\", status_code=~\"4..|5..\"}[1m]) or vector(0))\n",
     "legendFormat": "errors per second"
    },
    {
     "expr": "sum(rate(grafana_http_request_duration_seconds_count{job=~\"grafana\",handler=~\"/api/datasources/proxy/:id/.*\",namespace=~\"$environment\", status_code=~\"4..|5..\"}[1m]) or vector(0))\n/\nsum(rate(grafana_http_request_duration_seconds_count{job=~\"grafana\",handler=~\"/api/datasources/proxy/:id/.*\",namespace=~\"$environment\"}[1m]))\n",
     "legendFormat": "error rate"
    }
   ]
  },
  {
   "title": "SLI04: requests to the Grafana datasources are successful",
   "type": "row"
  },
  {
   "title": " Availability (7d)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI04\", journey=\"grafana\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"}\n< bool 0.10000000000000001)[7d:1m]))\n/\nsum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI04\", journey=\"grafana\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"}\n< bool Inf)[7d:1m]) > 0)\n",
     "legendFormat": "SLO Target 90.0 %"
    }
   ]
  },
  {
   "title": "Error budget remaining over previous 7d",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(0.10000000000000001 - (1 - (sum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI04\", journey=\"grafana\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"}\n< bool 0.10000000000000001)[7d:1m]))\n/\nsum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI04\", journey=\"grafana\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"}\n< bool Inf)[7d:1m])))))\n/\n0.10000000000000001\n",
     "legendFormat": "Remaining Error Budget"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 0.5, "x": 14, "y": 0 } },
  {
   "type": "graph",
   "description": "Error rate for Grafana  datasource API requests should be below 10.0%",
   "gridPos": { "h": 1, "w": 9, "x": 14.5, "y": 0 },
   "targets": [
    {
     "expr": "sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI04\", journey=\"grafana\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} < bool 0.10000000000000001)[$__interval:1m])\n/ \nsum_over_time((sli_value{service=\"monitoring\", sli=\"SLI04\", journey=\"grafana\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} < bool Inf)[$__interval:1m])\n",
     "legendFormat": "SLO OK"
    },
    {
     "expr": "1 - (\n  sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI04\", journey=\"grafana\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} < bool 0.10000000000000001)[$__interval:1m])\n  / \n  sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI04\", journey=\"grafana\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} < bool Inf)[$__interval:1m])\n)\n",
     "legendFormat": "SLO Fail"
    }
   ]
  },
  {
   "title": "Grafana  datasource API requests",
   "type": "graph",
   "description": "* Sample interval is 1m\n* Selectors are job=\\~\"grafana\"\n* Error selectors are code=~\"4..|5..\"\n",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grafana_api_response_status_total{job=~\"grafana\",namespace=~\"$environment\"}[1m]))\n",
     "legendFormat": "requests per second"
    },
    {
     "expr": "sum(rate(grafana_api_response_status_total{job=~\"grafana\",namespace=~\"$environment\", code=~\"4..|5..\"}[1m]) or vector(0))\n",
     "legendFormat": "errors per second"
    },
    {
     "expr": "sum(rate(grafana_api_response_status_total{job=~\"grafana\",namespace=~\"$environment\", code=~\"4..|5..\"}[1m]) or vector(0))\n/\nsum(rate(grafana_api_response_status_total{job=~\"grafana\",namespace=~\"$environment\"}[1m]))\n",
     "legendFormat": "error rate"
    }
   ]
  }
 ]
}