{
 "title": "monitoring-product-view",
 "tags": [
  "monitoring",
  "mac-version: local",
  "product-view"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(sli_value{service=\"monitoring\"}, sli_environment)"
   }
  ]
 },
 "panels": [
  { "title": "grafana", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SLI01 (7d)",
   "type": "stat",
   "description": "Grafana landing page requests",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( sum( sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI01\", journey=\"grafana\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} < bool 0.10000000000000001)[7d:1m]) )\n/ \nsum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI01\", journey=\"grafana\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} < bool Inf)[7d:1m]) > 0)\n  ) / 1\n",
     "legendFormat": "SLO Target 90.0 %"
    }
   ]
  },
  {
   "title": "SLI02 (7d)",
   "type": "stat",
   "description": "Grafana login page requests",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( sum( sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI02\", journey=\"grafana\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} < bool 0.10000000000000001)[7d:1m]) )\n/ \nsum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI02\", journey=\"grafana\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} < bool Inf)[7d:1m]) > 0)\n  ) / 1\n",
     "legendFormat": "SLO Target 90.0 %"
    }
   ]
  },
  {
   "title": "SLI03 (7d)",
   "type": "stat",
   "description": "Grafana  datasource API requests",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( sum( sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI03\", journey=\"grafana\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} < bool 0.5)[7d:1m]) )\n/ \nsum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI03\", journey=\"grafana\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} < bool Inf)[7d:1m]) > 0)\n  ) / 1\n",
     "legendFormat": "SLO Target 90.0 %"
    }
   ]
  },
  {
   "title": "SLI04 (7d)",
   "type": "stat",
   "description": "Grafana  datasource API requests",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( sum( sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI04\", journey=\"grafana\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} < bool 0.10000000000000001)[7d:1m]) )\n/ \nsum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI04\", journey=\"grafana\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} < bool Inf)[7d:1m]) > 0)\n  ) / 1\n",
     "legendFormat": "SLO Target 90.0 %"
    }
   ]
  },
  { "title": "prometheus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "SLI01 (7d)",
   "type": "stat",
   "description": "Average of prometheus scrape target status",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( sum( sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI01\", journey=\"prometheus\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} == bool 1)[7d:1m]) )\n/ \nsum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI01\", journey=\"prometheus\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} < bool Inf)[7d:1m]) > 0)\n  ) / 1\n",
     "legendFormat": "SLO Target 90.0 %"
    }
   ]
  },
  {
   "title": "SLI02 (7d)",
   "type": "stat",
   "description": "Average duration of Prometheus scrape of Yace",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( sum( sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI02\", journey=\"prometheus\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} < bool 15)[7d:1m]) )\n/ \nsum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI02\", journey=\"prometheus\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} < bool Inf)[7d:1m]) > 0)\n  ) / 1\n",
     "legendFormat": "SLO Target 90.0 %"
    }
   ]
  },
  { "title": "thanos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "SLI01 (7d)",
   "type": "stat",
   "description": "Instant query requests to thanos-query",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( sum( sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI01\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} < bool 0.10000000000000001)[7d:1m]) )\n/ \nsum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI01\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} < bool Inf)[7d:1m]) > 0)\n  ) / 1\n",
     "legendFormat": "SLO Target 90.0 %"
    }
   ]
  },
  {
   "title": "SLI02 (7d)",
   "type": "stat",
   "description": "Instant query requests to thanos-query",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( sum( sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI02\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"latency\"} < bool 15)[7d:1m]) )\n/ \nsum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI02\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"latency\"} < bool Inf)[7d:1m]) > 0)\n  ) / 1\n",
     "legendFormat": "SLO Target 90.0 %"
    }
   ]
  },
  {
   "title": "SLI03 (7d)",
   "type": "stat",
   "description": "Range query requests to thanos-query",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( sum( sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI03\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} < bool 0.10000000000000001)[7d:1m]) )\n/ \nsum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI03\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} < bool Inf)[7d:1m]) > 0)\n  ) / 1\n",
     "legendFormat": "SLO Target 90.0 %"
    }
   ]
  },
  {
   "title": "SLI04 (7d)",
   "type": "stat",
   "description": "Range query requests to thanos-query",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( sum( sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI04\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"latency\"} < bool 10)[7d:1m]) )\n/ \nsum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI04\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"latency\"} < bool Inf)[7d:1m]) > 0)\n  ) / 1\n",
     "legendFormat": "SLO Target 90.0 %"
    }
   ]
  },
  {
   "title": "SLI05 (7d)",
   "type": "stat",
   "description": "Thanos-compact operations and failures",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( sum( sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI05\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} < bool 0.01)[7d:1m]) )\n/ \nsum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI05\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} < bool Inf)[7d:1m]) > 0)\n  ) / 1\n",
     "legendFormat": "SLO Target 99.0 %"
    }
   ]
  }
 ]
}