{
 "title": "monitoring-thanos-journey-view",
 "tags": [
  "monitoring",
  "mac-version: local",
  "thanos",
  "journey-view"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "error_budget_span", "label": "Error Budget Display", "query": "10m,1h,1d,7d,21d,30d,90d" },
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(sli_value{service=\"monitoring\"}, sli_environment)"
   }
  ]
 },
 "panels": [
  {
   "title": "SLI01: instant query requests to Thanos",
   "type": "row"
  },
  {
   "title": " Availability (7d)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI01\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"}\n< bool 0.10000000000000001)[7d:1m]))\n/\nsum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI01\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"}\n< bool Inf)[7d:1m]) > 0)\n",
     "legendFormat": "SLO Target 90.0 %"
    }
   ]
  },
  {
   "title": "Error budget remaining over previous 7d",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(0.10000000000000001 - (1 - (sum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI01\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"}\n< bool 0.10000000000000001)[7d:1m]))\n/\nsum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI01\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"}\n< bool Inf)[7d:1m])))))\n/\n0.10000000000000001\n",
     "legendFormat": "Remaining Error Budget"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 0.5, "x": 14, "y": 0 } },
  {
   "type": "graph",
   "description": "Error rate for Instant query requests to thanos-query should be below 10.0%",
   "gridPos": { "h": 1, "w": 9, "x": 14.5, "y": 0 },
   "targets": [
    {
     "expr": "sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI01\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} < bool 0.10000000000000001)[$__interval:1m])\n/ \nsum_over_time((sli_value{service=\"monitoring\", sli=\"SLI01\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} < bool Inf)[$__interval:1m])\n",
     "legendFormat": "SLO OK"
    },
    {
     "expr": "1 - (\n  sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI01\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} < bool 0.10000000000000001)[$__interval:1m])\n  / \n  sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI01\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} < bool Inf)[$__interval:1m])\n)\n",
     "legendFormat": "SLO Fail"
    }
   ]
  },
  {
   "title": "Instant query requests to thanos-query",
   "type": "graph",
   "description": "* Sample interval is 1m\n* Selectors are job=\\~\"thanos-query\", handler=\\~\"query\"\n* Error selectors are code=~\"4..|5..\"\n",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=~\"thanos-query\",handler=~\"query\",namespace=~\"$environment\"}[1m]))\n",
     "legendFormat": "requests per second"
    },
    {
     "expr": "sum(rate(http_requests_total{job=~\"thanos-query\",handler=~\"query\",namespace=~\"$environment\", code=~\"4..|5..\"}[1m]) or vector(0))\n",
     "legendFormat": "errors per second"
    },
    {
     "expr": "sum(rate(http_requests_total{job=~\"thanos-query\",handler=~\"query\",namespace=~\"$environment\", code=~\"4..|5..\"}[1m]) or vector(0))\n/\nsum(rate(http_requests_total{job=~\"thanos-query\",handler=~\"query\",namespace=~\"$environment\"}[1m]))\n",
     "legendFormat": "error rate"
    }
   ]
  },
  {
   "title": "SLI02: instant query requests to Thanos are fast enough",
   "type": "row"
  },
  {
   "title": " Latency (7d)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI02\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"latency\"}\n< bool 15)[7d:1m]))\n/\nsum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI02\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"latency\"}\n< bool Inf)[7d:1m]) > 0)\n",
     "legendFormat": "SLO Target 90.0 %"
    }
   ]
  },
  {
   "title": "Error budget remaining over previous 7d",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(0.10000000000000001 - (1 - (sum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI02\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"latency\"}\n< bool 15)[7d:1m]))\n/\nsum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI02\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"latency\"}\n< bool Inf)[7d:1m])))))\n/\n0.10000000000000001\n",
     "legendFormat": "Remaining Error Budget"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 0.5, "x": 14, "y": 0 } },
  {
   "type": "graph",
   "description": "Request latency for Instant query requests to thanos-query should be below 15.0s for the 80th percentile",
   "gridPos": { "h": 1, "w": 9, "x": 14.5, "y": 0 },
   "targets": [
    {
     "expr": "sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI02\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"latency\"} < bool 15)[$__interval:1m])\n/ \nsum_over_time((sli_value{service=\"monitoring\", sli=\"SLI02\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"latency\"} < bool Inf)[$__interval:1m])\n",
     "legendFormat": "SLO OK"
    },
    {
     "expr": "1 - (\n  sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI02\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"latency\"} < bool 15)[$__interval:1m])\n  / \n  sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI02\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"latency\"} < bool Inf)[$__interval:1m])\n)\n",
     "legendFormat": "SLO Fail"
    }
   ]
  },
  {
   "title": "Instant query requests to thanos-query",
   "type": "graph",
   "description": "* Sample interval is 1m\n* Selectors are job=\\~\"thanos-query\", handler=\\~\"query\"\n",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{job=~\"thanos-query\",handler=~\"query\",namespace=~\"$environment\"}[1m]) or vector(0)) / \nsum(rate(http_request_duration_seconds_count{job=~\"thanos-query\",handler=~\"query\",namespace=~\"$environment\"}[1m]) or vector(0))\n",
     "legendFormat": "average latency"
    }
   ]
  },
  {
   "title": "SLI03: range query requests to Thanos",
   "type": "row"
  },
  {
   "title": " Availability (7d)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI03\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"}\n< bool 0.10000000000000001)[7d:1m]))\n/\nsum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI03\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"}\n< bool Inf)[7d:1m]) > 0)\n",
     "legendFormat": "SLO Target 90.0 %"
    }
   ]
  },
  {
   "title": "Error budget remaining over previous 7d",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(0.10000000000000001 - (1 - (sum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI03\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"}\n< bool 0.10000000000000001)[7d:1m]))\n/\nsum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI03\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"}\n< bool Inf)[7d:1m])))))\n/\n0.10000000000000001\n",
     "legendFormat": "Remaining Error Budget"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 0.5, "x": 14, "y": 0 } },
  {
   "type": "graph",
   "description": "Error rate for Range query requests to thanos-query should be below 10.0%",
   "gridPos": { "h": 1, "w": 9, "x": 14.5, "y": 0 },
   "targets": [
    {
     "expr": "sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI03\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} < bool 0.10000000000000001)[$__interval:1m])\n/ \nsum_over_time((sli_value{service=\"monitoring\", sli=\"SLI03\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} < bool Inf)[$__interval:1m])\n",
     "legendFormat": "SLO OK"
    },
    {
     "expr": "1 - (\n  sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI03\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} < bool 0.10000000000000001)[$__interval:1m])\n  / \n  sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI03\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} < bool Inf)[$__interval:1m])\n)\n",
     "legendFormat": "SLO Fail"
    }
   ]
  },
  {
   "title": "Range query requests to thanos-query",
   "type": "graph",
   "description": "* Sample interval is 1m\n* Selectors are job=\\~\"thanos-query\", handler=\\~\"query_range\"\n* Error selectors are code=~\"4..|5..\"\n",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=~\"thanos-query\",handler=~\"query_range\",namespace=~\"$environment\"}[1m]))\n",
     "legendFormat": "requests per second"
    },
    {
     "expr": "sum(rate(http_requests_total{job=~\"thanos-query\",handler=~\"query_range\",namespace=~\"$environment\", code=~\"4..|5..\"}[1m]) or vector(0))\n",
     "legendFormat": "errors per second"
    },
    {
     "expr": "sum(rate(http_requests_total{job=~\"thanos-query\",handler=~\"query_range\",namespace=~\"$environment\", code=~\"4..|5..\"}[1m]) or vector(0))\n/\nsum(rate(http_requests_total{job=~\"thanos-query\",handler=~\"query_range\",namespace=~\"$environment\"}[1m]))\n",
     "legendFormat": "error rate"
    }
   ]
  },
  {
   "title": "SLI04: range query requests to Thanos are fast enough",
   "type": "row"
  },
  {
   "title": " Latency (7d)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI04\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"latency\"}\n< bool 10)[7d:1m]))\n/\nsum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI04\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"latency\"}\n< bool Inf)[7d:1m]) > 0)\n",
     "legendFormat": "SLO Target 90.0 %"
    }
   ]
  },
  {
   "title": "Error budget remaining over previous 7d",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(0.10000000000000001 - (1 - (sum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI04\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"latency\"}\n< bool 10)[7d:1m]))\n/\nsum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI04\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"latency\"}\n< bool Inf)[7d:1m])))))\n/\n0.10000000000000001\n",
     "legendFormat": "Remaining Error Budget"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 0.5, "x": 14, "y": 0 } },
  {
   "type": "graph",
   "description": "Request latency for Range query requests to thanos-query should be below 10.0s for the 80th percentile",
   "gridPos": { "h": 1, "w": 9, "x": 14.5, "y": 0 },
   "targets": [
    {
     "expr": "sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI04\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"latency\"} < bool 10)[$__interval:1m])\n/ \nsum_over_time((sli_value{service=\"monitoring\", sli=\"SLI04\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"latency\"} < bool Inf)[$__interval:1m])\n",
     "legendFormat": "SLO OK"
    },
    {
     "expr": "1 - (\n  sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI04\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"latency\"} < bool 10)[$__interval:1m])\n  / \n  sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI04\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"latency\"} < bool Inf)[$__interval:1m])\n)\n",
     "legendFormat": "SLO Fail"
    }
   ]
  },
  {
   "title": "Range query requests to thanos-query",
   "type": "graph",
   "description": "* Sample interval is 1m\n* Selectors are job=\\~\"thanos-query\", handler=\\~\"query_range\"\n",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{job=~\"thanos-query\",handler=~\"query_range\",namespace=~\"$environment\"}[1m]) or vector(0)) / \nsum(rate(http_request_duration_seconds_count{job=~\"thanos-query\",handler=~\"query_range\",namespace=~\"$environment\"}[1m]) or vector(0))\n",
     "legendFormat": "average latency"
    }
   ]
  },
  {
   "title": "SLI05: compactions by thanos-compact",
   "type": "row"
  },
  {
   "title": " Availability (7d)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI05\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"}\n< bool 0.01)[7d:1m]))\n/\nsum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI05\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"}\n< bool Inf)[7d:1m]) > 0)\n",
     "legendFormat": "SLO Target 99.0 %"
    }
   ]
  },
  {
   "title": "Error budget remaining over previous 7d",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(0.01 - (1 - (sum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI05\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"}\n< bool 0.01)[7d:1m]))\n/\nsum(sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI05\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"}\n< bool Inf)[7d:1m])))))\n/\n0.01\n",
     "legendFormat": "Remaining Error Budget"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 0.5, "x": 14, "y": 0 } },
  {
   "type": "graph",
   "description": "The rate of Thanos-compact operations and failures should be below 1.0%",
   "gridPos": { "h": 1, "w": 9, "x": 14.5, "y": 0 },
   "targets": [
    {
     "expr": "sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI05\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} < bool 0.01)[$__interval:1m])\n/ \nsum_over_time((sli_value{service=\"monitoring\", sli=\"SLI05\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} < bool Inf)[$__interval:1m])\n",
     "legendFormat": "SLO OK"
    },
    {
     "expr": "1 - (\n  sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI05\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} < bool 0.01)[$__interval:1m])\n  / \n  sum_over_time((sli_value{service=\"monitoring\", sli=\"SLI05\", journey=\"thanos\",\nsli_environment=~\"$environment\"\n, sli_type=\"availability\"} < bool Inf)[$__interval:1m])\n)\n",
     "legendFormat": "SLO Fail"
    }
   ]
  },
  {
   "title": "Thanos-compact operations and failures",
   "type": "graph",
   "description": "* Sample interval is 1m\n* Selectors are job=\\~\"monitoring-thanos-compact.*\"\n",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_compact_group_compactions_total{job=~\"monitoring-thanos-compact.*\",namespace=~\"$environment\"}[1m]) or vector(0))\n",
     "legendFormat": "total per second"
    },
    {
     "expr": "sum(rate(thanos_compact_group_compactions_failures_total{job=~\"monitoring-thanos-compact.*\",namespace=~\"$environment\"}[1m]) or vector(0))\n",
     "legendFormat": "errors per second"
    },
    {
     "expr": "sum(rate(thanos_compact_group_compactions_failures_total{job=~\"monitoring-thanos-compact.*\",namespace=~\"$environment\"}[1m]))\n/\nsum(rate(thanos_compact_group_compactions_total{job=~\"monitoring-thanos-compact.*\",namespace=~\"$environment\"}[1m]))\n",
     "legendFormat": "errors rate"
    }
   ]
  }
 ]
}