{
 "title": "monitoring-product-view",
 "tags": [
  "monitoring",
  "product-view"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "environment", "label": "Environment", "query": "label_values(environment)" }
  ]
 },
 "panels": [
  {
   "title": "SLO Summary for grafana journey",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "SLI01 (7d)",
   "type": "stat",
   "description": "SLI01: Percentage of time requests to the Grafana landing page are successful",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(slo_ok{service='monitoring',slo='SLI01',environment='$environment',journey='grafana'}[7d])) / sum(sum_over_time(slo_sample{service='monitoring',slo='SLI01',environment='$environment',journey='grafana'}[7d]) > 0)",
     "legendFormat": "SLO Target 90%"
    }
   ]
  },
  {
   "title": "SLI02 (7d)",
   "type": "stat",
   "description": "SLI02: Percentage of time requests to the Grafana login are successful",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(slo_ok{service='monitoring',slo='SLI02',environment='$environment',journey='grafana'}[7d])) / sum(sum_over_time(slo_sample{service='monitoring',slo='SLI02',environment='$environment',journey='grafana'}[7d]) > 0)",
     "legendFormat": "SLO Target 90%"
    }
   ]
  },
  {
   "title": "SLI03 (7d)",
   "type": "stat",
   "description": "SLI03: Percentage of time requests to the Grafana datasources are successful",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(slo_ok{service='monitoring',slo='SLI03',environment='$environment',journey='grafana'}[7d])) / sum(sum_over_time(slo_sample{service='monitoring',slo='SLI03',environment='$environment',journey='grafana'}[7d]) > 0)",
     "legendFormat": "SLO Target 90%"
    }
   ]
  },
  {
   "title": "SLO Summary for prometheus journey",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }
  },
  {
   "title": "SLI01 (7d)",
   "type": "stat",
   "description": "SLI01: Percentage of time all prometheus scrape targets are available",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(slo_ok{service='monitoring',slo='SLI01',environment='$environment',journey='prometheus'}[7d])) / sum(sum_over_time(slo_sample{service='monitoring',slo='SLI01',environment='$environment',journey='prometheus'}[7d]) > 0)",
     "legendFormat": "SLO Target 90%"
    }
   ]
  },
  {
   "title": "SLI02 (7d)",
   "type": "stat",
   "description": "SLI02: Percentage of time prometheus scraping of Yace is fast enough",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(slo_ok{service='monitoring',slo='SLI02',environment='$environment',journey='prometheus'}[7d])) / sum(sum_over_time(slo_sample{service='monitoring',slo='SLI02',environment='$environment',journey='prometheus'}[7d]) > 0)",
     "legendFormat": "SLO Target 90%"
    }
   ]
  },
  { "title": "SLO Summary for thanos journey", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "SLI01 (7d)",
   "type": "stat",
   "description": "SLI01: Percentage of time instant query requests to Thanos",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(slo_ok{service='monitoring',slo='SLI01',environment='$environment',journey='thanos'}[7d])) / sum(sum_over_time(slo_sample{service='monitoring',slo='SLI01',environment='$environment',journey='thanos'}[7d]) > 0)",
     "legendFormat": "SLO Target 90%"
    }
   ]
  },
  {
   "title": "SLI02 (7d)",
   "type": "stat",
   "description": "SLI02: Percentage of time instant query requests to Thanos are fast enough",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(slo_ok{service='monitoring',slo='SLI02',environment='$environment',journey='thanos'}[7d])) / sum(sum_over_time(slo_sample{service='monitoring',slo='SLI02',environment='$environment',journey='thanos'}[7d]) > 0)",
     "legendFormat": "SLO Target 90%"
    }
   ]
  },
  {
   "title": "SLI03 (7d)",
   "type": "stat",
   "description": "SLI03: Percentage of time range query requests to Thanos",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(slo_ok{service='monitoring',slo='SLI03',environment='$environment',journey='thanos'}[7d])) / sum(sum_over_time(slo_sample{service='monitoring',slo='SLI03',environment='$environment',journey='thanos'}[7d]) > 0)",
     "legendFormat": "SLO Target 90%"
    }
   ]
  },
  {
   "title": "SLI04 (7d)",
   "type": "stat",
   "description": "SLI04: Percentage of time range query requests to Thanos are fast enough",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(slo_ok{service='monitoring',slo='SLI04',environment='$environment',journey='thanos'}[7d])) / sum(sum_over_time(slo_sample{service='monitoring',slo='SLI04',environment='$environment',journey='thanos'}[7d]) > 0)",
     "legendFormat": "SLO Target 90%"
    }
   ]
  },
  {
   "title": "SLI05 (7d)",
   "type": "stat",
   "description": "SLI05: Percentage of time compactions by thanos-compact",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(slo_ok{service='monitoring',slo='SLI05',environment='$environment',journey='thanos'}[7d])) / sum(sum_over_time(slo_sample{service='monitoring',slo='SLI05',environment='$environment',journey='thanos'}[7d]) > 0)",
     "legendFormat": "SLO Target 99%"
    }
   ]
  }
 ]
}