{
 "title": "monitoring-thanos-journey-view",
 "tags": [
  "monitoring",
  "thanos",
  "journey-view"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "error_budget_span", "label": "Error Budget Display", "query": "10m,1h,1d,7d,21d,30d,90d" },
   { "name": "environment", "label": "Environment", "query": "label_values(environment)" }
  ]
 },
 "panels": [
  {
   "title": "SLI01: Percentage of time instant query requests to Thanos",
   "type": "row"
  },
  {
   "title": "SLO Performance (7d)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(slo_ok{service='monitoring',slo='SLI01',environment='$environment',journey='thanos'}[7d])) / sum(sum_over_time(slo_sample{service='monitoring',slo='SLI01',environment='$environment',journey='thanos'}[7d]) > 0)",
     "legendFormat": "SLO Target 90%"
    }
   ]
  },
  {
   "title": "Error budget remaining over previous 7d",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(0.10000000000000001 - (1 - (sum(sum_over_time( slo_ok{service='monitoring',slo='SLI01',environment='$environment',journey='thanos'}[7d] ))  / sum(sum_over_time(slo_sample{service='monitoring',slo='SLI01',environment='$environment',journey='thanos'}[7d]) ) ) ) ) / 0.10000000000000001",
     "legendFormat": "Remaining Error Budget"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 0.5, "x": 14, "y": 0 } },
  {
   "type": "graph",
   "description": "Error rate for Instant query requests to thanos-query should be below 10.0%",
   "gridPos": { "h": 1, "w": 9, "x": 14.5, "y": 0 },
   "targets": [
    {
     "expr": "sum_over_time ( slo_ok { service='monitoring',slo='SLI01',environment='$environment',journey='thanos' } [ $__interval ] )\n/ \nsum_over_time ( slo_sample { service='monitoring',slo='SLI01',environment='$environment',journey='thanos' } [ $__interval ] )\n",
     "legendFormat": "SLO OK"
    },
    {
     "expr": "1 - (\n  sum_over_time ( slo_ok { service='monitoring',slo='SLI01',environment='$environment',journey='thanos' } [ $__interval ] )\n  / \n  sum_over_time ( slo_sample { service='monitoring',slo='SLI01',environment='$environment',journey='thanos' } [ $__interval ] )\n)\n",
     "legendFormat": "SLO Fail"
    }
   ]
  },
  {
   "title": "Requests, errors, and error rate - Instant query requests to thanos-query",
   "type": "graph",
   "description": "* Sample interval is 1m \n* Request selectors are job=\\~\"thanos-query\" , handler=\"query\" \n* Error selectors are code=\\~\"4..|5..\"\n",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=~\"thanos-query\",handler=\"query\",host=\"$environment\"}[1m]) or vector(0))",
     "legendFormat": "Requests per second"
    },
    {
     "expr": "sum(rate(http_requests_total{job=~\"thanos-query\",handler=\"query\",host=\"$environment\",code=~\"4..|5..\"}[1m]) or vector(0))",
     "legendFormat": "Errors per second"
    },
    {
     "expr": "sum(rate(http_requests_total{job=~\"thanos-query\",handler=\"query\",host=\"$environment\",code=~\"4..|5..\"}[1m]) or vector(0)) / sum(rate(http_requests_total{job=~\"thanos-query\",handler=\"query\",host=\"$environment\"}[1m]) or vector(0))",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "SLI02: Percentage of time instant query requests to Thanos are fast enough",
   "type": "row"
  },
  {
   "title": "SLO Performance (7d)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(slo_ok{service='monitoring',slo='SLI02',environment='$environment',journey='thanos'}[7d])) / sum(sum_over_time(slo_sample{service='monitoring',slo='SLI02',environment='$environment',journey='thanos'}[7d]) > 0)",
     "legendFormat": "SLO Target 90%"
    }
   ]
  },
  {
   "title": "Error budget remaining over previous 7d",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(0.10000000000000001 - (1 - (sum(sum_over_time( slo_ok{service='monitoring',slo='SLI02',environment='$environment',journey='thanos'}[7d] ))  / sum(sum_over_time(slo_sample{service='monitoring',slo='SLI02',environment='$environment',journey='thanos'}[7d]) ) ) ) ) / 0.10000000000000001",
     "legendFormat": "Remaining Error Budget"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 0.5, "x": 14, "y": 0 } },
  {
   "type": "graph",
   "description": "Request latency for Instant query requests to thanos-query should be below 15.0s for the 80th percentile",
   "gridPos": { "h": 1, "w": 9, "x": 14.5, "y": 0 },
   "targets": [
    {
     "expr": "sum_over_time ( slo_ok { service='monitoring',slo='SLI02',environment='$environment',journey='thanos' } [ $__interval ] )\n/ \nsum_over_time ( slo_sample { service='monitoring',slo='SLI02',environment='$environment',journey='thanos' } [ $__interval ] )\n",
     "legendFormat": "SLO OK"
    },
    {
     "expr": "1 - (\n  sum_over_time ( slo_ok { service='monitoring',slo='SLI02',environment='$environment',journey='thanos' } [ $__interval ] )\n  / \n  sum_over_time ( slo_sample { service='monitoring',slo='SLI02',environment='$environment',journey='thanos' } [ $__interval ] )\n)\n",
     "legendFormat": "SLO Fail"
    }
   ]
  },
  {
   "title": "Latency - Instant query requests to thanos-query",
   "type": "graph",
   "description": "* Sample interval is 1m \n* Request selectors are job=\\~\"thanos-query\" , handler=\"query\" \n",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{job=~\"thanos-query\",handler=\"query\",host=\"$environment\"}[1m]) or vector(0)) /  sum(rate(http_request_duration_seconds_count{job=~\"thanos-query\",handler=\"query\",host=\"$environment\"}[1m]) or vector(0))",
     "legendFormat": "Average Latency"
    }
   ]
  },
  {
   "title": "SLI03: Percentage of time range query requests to Thanos",
   "type": "row"
  },
  {
   "title": "SLO Performance (7d)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(slo_ok{service='monitoring',slo='SLI03',environment='$environment',journey='thanos'}[7d])) / sum(sum_over_time(slo_sample{service='monitoring',slo='SLI03',environment='$environment',journey='thanos'}[7d]) > 0)",
     "legendFormat": "SLO Target 90%"
    }
   ]
  },
  {
   "title": "Error budget remaining over previous 7d",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(0.10000000000000001 - (1 - (sum(sum_over_time( slo_ok{service='monitoring',slo='SLI03',environment='$environment',journey='thanos'}[7d] ))  / sum(sum_over_time(slo_sample{service='monitoring',slo='SLI03',environment='$environment',journey='thanos'}[7d]) ) ) ) ) / 0.10000000000000001",
     "legendFormat": "Remaining Error Budget"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 0.5, "x": 14, "y": 0 } },
  {
   "type": "graph",
   "description": "Error rate for Range query requests to thanos-query should be below 10.0%",
   "gridPos": { "h": 1, "w": 9, "x": 14.5, "y": 0 },
   "targets": [
    {
     "expr": "sum_over_time ( slo_ok { service='monitoring',slo='SLI03',environment='$environment',journey='thanos' } [ $__interval ] )\n/ \nsum_over_time ( slo_sample { service='monitoring',slo='SLI03',environment='$environment',journey='thanos' } [ $__interval ] )\n",
     "legendFormat": "SLO OK"
    },
    {
     "expr": "1 - (\n  sum_over_time ( slo_ok { service='monitoring',slo='SLI03',environment='$environment',journey='thanos' } [ $__interval ] )\n  / \n  sum_over_time ( slo_sample { service='monitoring',slo='SLI03',environment='$environment',journey='thanos' } [ $__interval ] )\n)\n",
     "legendFormat": "SLO Fail"
    }
   ]
  },
  {
   "title": "Requests, errors, and error rate - Range query requests to thanos-query",
   "type": "graph",
   "description": "* Sample interval is 1m \n* Request selectors are job=\\~\"thanos-query\" , handler=\"query_range\" \n* Error selectors are code=\\~\"4..|5..\"\n",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=~\"thanos-query\",handler=\"query_range\",host=\"$environment\"}[1m]) or vector(0))",
     "legendFormat": "Requests per second"
    },
    {
     "expr": "sum(rate(http_requests_total{job=~\"thanos-query\",handler=\"query_range\",host=\"$environment\",code=~\"4..|5..\"}[1m]) or vector(0))",
     "legendFormat": "Errors per second"
    },
    {
     "expr": "sum(rate(http_requests_total{job=~\"thanos-query\",handler=\"query_range\",host=\"$environment\",code=~\"4..|5..\"}[1m]) or vector(0)) / sum(rate(http_requests_total{job=~\"thanos-query\",handler=\"query_range\",host=\"$environment\"}[1m]) or vector(0))",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "SLI04: Percentage of time range query requests to Thanos are fast enough",
   "type": "row"
  },
  {
   "title": "SLO Performance (7d)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(slo_ok{service='monitoring',slo='SLI04',environment='$environment',journey='thanos'}[7d])) / sum(sum_over_time(slo_sample{service='monitoring',slo='SLI04',environment='$environment',journey='thanos'}[7d]) > 0)",
     "legendFormat": "SLO Target 90%"
    }
   ]
  },
  {
   "title": "Error budget remaining over previous 7d",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(0.10000000000000001 - (1 - (sum(sum_over_time( slo_ok{service='monitoring',slo='SLI04',environment='$environment',journey='thanos'}[7d] ))  / sum(sum_over_time(slo_sample{service='monitoring',slo='SLI04',environment='$environment',journey='thanos'}[7d]) ) ) ) ) / 0.10000000000000001",
     "legendFormat": "Remaining Error Budget"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 0.5, "x": 14, "y": 0 } },
  {
   "type": "graph",
   "description": "Request latency for Range query requests to thanos-query should be below 10.0s for the 80th percentile",
   "gridPos": { "h": 1, "w": 9, "x": 14.5, "y": 0 },
   "targets": [
    {
     "expr": "sum_over_time ( slo_ok { service='monitoring',slo='SLI04',environment='$environment',journey='thanos' } [ $__interval ] )\n/ \nsum_over_time ( slo_sample { service='monitoring',slo='SLI04',environment='$environment',journey='thanos' } [ $__interval ] )\n",
     "legendFormat": "SLO OK"
    },
    {
     "expr": "1 - (\n  sum_over_time ( slo_ok { service='monitoring',slo='SLI04',environment='$environment',journey='thanos' } [ $__interval ] )\n  / \n  sum_over_time ( slo_sample { service='monitoring',slo='SLI04',environment='$environment',journey='thanos' } [ $__interval ] )\n)\n",
     "legendFormat": "SLO Fail"
    }
   ]
  },
  {
   "title": "Latency - Range query requests to thanos-query",
   "type": "graph",
   "description": "* Sample interval is 1m \n* Request selectors are job=\\~\"thanos-query\" , handler=\"query_range\" \n",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{job=~\"thanos-query\",handler=\"query_range\",host=\"$environment\"}[1m]) or vector(0)) /  sum(rate(http_request_duration_seconds_count{job=~\"thanos-query\",handler=\"query_range\",host=\"$environment\"}[1m]) or vector(0))",
     "legendFormat": "Average Latency"
    }
   ]
  },
  {
   "title": "SLI05: Percentage of time compactions by thanos-compact",
   "type": "row"
  },
  {
   "title": "SLO Performance (7d)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(slo_ok{service='monitoring',slo='SLI05',environment='$environment',journey='thanos'}[7d])) / sum(sum_over_time(slo_sample{service='monitoring',slo='SLI05',environment='$environment',journey='thanos'}[7d]) > 0)",
     "legendFormat": "SLO Target 99%"
    }
   ]
  },
  {
   "title": "Error budget remaining over previous 7d",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(0.01 - (1 - (sum(sum_over_time( slo_ok{service='monitoring',slo='SLI05',environment='$environment',journey='thanos'}[7d] ))  / sum(sum_over_time(slo_sample{service='monitoring',slo='SLI05',environment='$environment',journey='thanos'}[7d]) ) ) ) ) / 0.01",
     "legendFormat": "Remaining Error Budget"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 0.5, "x": 14, "y": 0 } },
  {
   "type": "graph",
   "description": "the rate of Thanos-compact operations and failures should be below 1.0%",
   "gridPos": { "h": 1, "w": 9, "x": 14.5, "y": 0 },
   "targets": [
    {
     "expr": "sum_over_time ( slo_ok { service='monitoring',slo='SLI05',environment='$environment',journey='thanos' } [ $__interval ] )\n/ \nsum_over_time ( slo_sample { service='monitoring',slo='SLI05',environment='$environment',journey='thanos' } [ $__interval ] )\n",
     "legendFormat": "SLO OK"
    },
    {
     "expr": "1 - (\n  sum_over_time ( slo_ok { service='monitoring',slo='SLI05',environment='$environment',journey='thanos' } [ $__interval ] )\n  / \n  sum_over_time ( slo_sample { service='monitoring',slo='SLI05',environment='$environment',journey='thanos' } [ $__interval ] )\n)\n",
     "legendFormat": "SLO Fail"
    }
   ]
  },
  {
   "title": "Thanos-compact operations and failures",
   "type": "graph",
   "description": "* Sample interval is 1m \n",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_compact_group_compactions_total{job=~\"monitoring-thanos-compact.*\",host=\"$environment\"}[1m]) or vector(0))",
     "legendFormat": "Total per second"
    },
    {
     "expr": "sum(rate(thanos_compact_group_compactions_failures_total{job=~\"monitoring-thanos-compact.*\",host=\"$environment\"}[1m]) or vector(0))",
     "legendFormat": "Errors per second"
    },
    {
     "expr": "sum(rate(thanos_compact_group_compactions_failures_total{job=~\"monitoring-thanos-compact.*\",host=\"$environment\"}[1m]) or vector(0)) / sum(rate(thanos_compact_group_compactions_total{job=~\"monitoring-thanos-compact.*\",host=\"$environment\"}[1m]) or vector(0))",
     "legendFormat": "Error rate"
    }
   ]
  }
 ]
}