{
 "title": "monitoring-grafana-journey-view",
 "tags": [
  "monitoring",
  "grafana",
  "journey-view"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "error_budget_span", "label": "Error Budget Display", "query": "10m,1h,1d,7d,21d,30d,90d" },
   { "name": "environment", "label": "Environment", "query": "label_values(environment)" }
  ]
 },
 "panels": [
  {
   "title": "SLI01: Percentage of time requests to the Grafana landing page are successful",
   "type": "row"
  },
  {
   "title": "SLO Performance (7d)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(slo_ok{service='monitoring',slo='SLI01',environment='$environment',journey='grafana'}[7d])) / sum(sum_over_time(slo_sample{service='monitoring',slo='SLI01',environment='$environment',journey='grafana'}[7d]) > 0)",
     "legendFormat": "SLO Target 90%"
    }
   ]
  },
  {
   "title": "Error budget remaining over previous 7d",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(0.10000000000000001 - (1 - (sum(sum_over_time( slo_ok{service='monitoring',slo='SLI01',environment='$environment',journey='grafana'}[7d] ))  / sum(sum_over_time(slo_sample{service='monitoring',slo='SLI01',environment='$environment',journey='grafana'}[7d]) ) ) ) ) / 0.10000000000000001",
     "legendFormat": "Remaining Error Budget"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 0.5, "x": 14, "y": 0 } },
  {
   "type": "graph",
   "description": "Error rate for Grafana landing page requests should be below 10.0%",
   "gridPos": { "h": 1, "w": 9, "x": 14.5, "y": 0 },
   "targets": [
    {
     "expr": "sum_over_time ( slo_ok { service='monitoring',slo='SLI01',environment='$environment',journey='grafana' } [ $__interval ] )\n/ \nsum_over_time ( slo_sample { service='monitoring',slo='SLI01',environment='$environment',journey='grafana' } [ $__interval ] )\n",
     "legendFormat": "SLO OK"
    },
    {
     "expr": "1 - (\n  sum_over_time ( slo_ok { service='monitoring',slo='SLI01',environment='$environment',journey='grafana' } [ $__interval ] )\n  / \n  sum_over_time ( slo_sample { service='monitoring',slo='SLI01',environment='$environment',journey='grafana' } [ $__interval ] )\n)\n",
     "legendFormat": "SLO Fail"
    }
   ]
  },
  {
   "title": "Requests, errors, and error rate - Grafana landing page requests",
   "type": "graph",
   "description": "* Sample interval is 1m \n* Request selectors are job=\"grafana\" , handler=\\~\"/api/dashboards/home\" \n* Error selectors are status_code=\\~\"4..|5..\"\n",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grafana_http_request_duration_seconds_count{job=\"grafana\",handler=~\"/api/dashboards/home\",host=\"$environment\"}[1m]) or vector(0))",
     "legendFormat": "Requests per second"
    },
    {
     "expr": "sum(rate(grafana_http_request_duration_seconds_count{job=\"grafana\",handler=~\"/api/dashboards/home\",host=\"$environment\",status_code=~\"4..|5..\"}[1m]) or vector(0))",
     "legendFormat": "Errors per second"
    },
    {
     "expr": "sum(rate(grafana_http_request_duration_seconds_count{job=\"grafana\",handler=~\"/api/dashboards/home\",host=\"$environment\",status_code=~\"4..|5..\"}[1m]) or vector(0)) / sum(rate(grafana_http_request_duration_seconds_count{job=\"grafana\",handler=~\"/api/dashboards/home\",host=\"$environment\"}[1m]) or vector(0))",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "SLI02: Percentage of time requests to the Grafana login are successful",
   "type": "row"
  },
  {
   "title": "SLO Performance (7d)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(slo_ok{service='monitoring',slo='SLI02',environment='$environment',journey='grafana'}[7d])) / sum(sum_over_time(slo_sample{service='monitoring',slo='SLI02',environment='$environment',journey='grafana'}[7d]) > 0)",
     "legendFormat": "SLO Target 90%"
    }
   ]
  },
  {
   "title": "Error budget remaining over previous 7d",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(0.10000000000000001 - (1 - (sum(sum_over_time( slo_ok{service='monitoring',slo='SLI02',environment='$environment',journey='grafana'}[7d] ))  / sum(sum_over_time(slo_sample{service='monitoring',slo='SLI02',environment='$environment',journey='grafana'}[7d]) ) ) ) ) / 0.10000000000000001",
     "legendFormat": "Remaining Error Budget"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 0.5, "x": 14, "y": 0 } },
  {
   "type": "graph",
   "description": "Error rate for Grafana login page requests should be below 10.0%",
   "gridPos": { "h": 1, "w": 9, "x": 14.5, "y": 0 },
   "targets": [
    {
     "expr": "sum_over_time ( slo_ok { service='monitoring',slo='SLI02',environment='$environment',journey='grafana' } [ $__interval ] )\n/ \nsum_over_time ( slo_sample { service='monitoring',slo='SLI02',environment='$environment',journey='grafana' } [ $__interval ] )\n",
     "legendFormat": "SLO OK"
    },
    {
     "expr": "1 - (\n  sum_over_time ( slo_ok { service='monitoring',slo='SLI02',environment='$environment',journey='grafana' } [ $__interval ] )\n  / \n  sum_over_time ( slo_sample { service='monitoring',slo='SLI02',environment='$environment',journey='grafana' } [ $__interval ] )\n)\n",
     "legendFormat": "SLO Fail"
    }
   ]
  },
  {
   "title": "Requests, errors, and error rate - Grafana login page requests",
   "type": "graph",
   "description": "* Sample interval is 1m \n* Request selectors are job=\"grafana\" , handler=\\~\"/login\" \n* Error selectors are status_code=\\~\"4..|5..\"\n",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grafana_http_request_duration_seconds_count{job=\"grafana\",handler=~\"/login\",host=\"$environment\"}[1m]) or vector(0))",
     "legendFormat": "Requests per second"
    },
    {
     "expr": "sum(rate(grafana_http_request_duration_seconds_count{job=\"grafana\",handler=~\"/login\",host=\"$environment\",status_code=~\"4..|5..\"}[1m]) or vector(0))",
     "legendFormat": "Errors per second"
    },
    {
     "expr": "sum(rate(grafana_http_request_duration_seconds_count{job=\"grafana\",handler=~\"/login\",host=\"$environment\",status_code=~\"4..|5..\"}[1m]) or vector(0)) / sum(rate(grafana_http_request_duration_seconds_count{job=\"grafana\",handler=~\"/login\",host=\"$environment\"}[1m]) or vector(0))",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "SLI03: Percentage of time requests to the Grafana datasources are successful",
   "type": "row"
  },
  {
   "title": "SLO Performance (7d)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(slo_ok{service='monitoring',slo='SLI03',environment='$environment',journey='grafana'}[7d])) / sum(sum_over_time(slo_sample{service='monitoring',slo='SLI03',environment='$environment',journey='grafana'}[7d]) > 0)",
     "legendFormat": "SLO Target 90%"
    }
   ]
  },
  {
   "title": "Error budget remaining over previous 7d",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(0.10000000000000001 - (1 - (sum(sum_over_time( slo_ok{service='monitoring',slo='SLI03',environment='$environment',journey='grafana'}[7d] ))  / sum(sum_over_time(slo_sample{service='monitoring',slo='SLI03',environment='$environment',journey='grafana'}[7d]) ) ) ) ) / 0.10000000000000001",
     "legendFormat": "Remaining Error Budget"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 0.5, "x": 14, "y": 0 } },
  {
   "type": "graph",
   "description": "Error rate for Grafana  datasource API requests should be below 50.0%",
   "gridPos": { "h": 1, "w": 9, "x": 14.5, "y": 0 },
   "targets": [
    {
     "expr": "sum_over_time ( slo_ok { service='monitoring',slo='SLI03',environment='$environment',journey='grafana' } [ $__interval ] )\n/ \nsum_over_time ( slo_sample { service='monitoring',slo='SLI03',environment='$environment',journey='grafana' } [ $__interval ] )\n",
     "legendFormat": "SLO OK"
    },
    {
     "expr": "1 - (\n  sum_over_time ( slo_ok { service='monitoring',slo='SLI03',environment='$environment',journey='grafana' } [ $__interval ] )\n  / \n  sum_over_time ( slo_sample { service='monitoring',slo='SLI03',environment='$environment',journey='grafana' } [ $__interval ] )\n)\n",
     "legendFormat": "SLO Fail"
    }
   ]
  },
  {
   "title": "Requests, errors, and error rate - Grafana  datasource API requests",
   "type": "graph",
   "description": "* Sample interval is 1m \n* Request selectors are job=\"grafana\" , handler=\\~\"/api/datasources/proxy/:id/*\" \n* Error selectors are status_code=\\~\"4..|5..\"\n",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grafana_http_request_duration_seconds_count{job=\"grafana\",handler=~\"/api/datasources/proxy/:id/*\",host=\"$environment\"}[1m]) or vector(0))",
     "legendFormat": "Requests per second"
    },
    {
     "expr": "sum(rate(grafana_http_request_duration_seconds_count{job=\"grafana\",handler=~\"/api/datasources/proxy/:id/*\",host=\"$environment\",status_code=~\"4..|5..\"}[1m]) or vector(0))",
     "legendFormat": "Errors per second"
    },
    {
     "expr": "sum(rate(grafana_http_request_duration_seconds_count{job=\"grafana\",handler=~\"/api/datasources/proxy/:id/*\",host=\"$environment\",status_code=~\"4..|5..\"}[1m]) or vector(0)) / sum(rate(grafana_http_request_duration_seconds_count{job=\"grafana\",handler=~\"/api/datasources/proxy/:id/*\",host=\"$environment\"}[1m]) or vector(0))",
     "legendFormat": "Error rate"
    }
   ]
  }
 ]
}