{
 "title": "monitoring-prometheus-journey-view",
 "tags": [
  "monitoring",
  "prometheus",
  "journey-view"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "error_budget_span", "label": "Error Budget Display", "query": "10m,1h,1d,7d,21d,30d,90d" },
   { "name": "environment", "label": "Environment", "query": "label_values(environment)" }
  ]
 },
 "panels": [
  {
   "title": "SLI01: Percentage of time all prometheus scrape targets are available",
   "type": "row"
  },
  {
   "title": "SLO Performance (7d)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(slo_ok{service='monitoring',slo='SLI01',environment='$environment',journey='prometheus'}[7d])) / sum(sum_over_time(slo_sample{service='monitoring',slo='SLI01',environment='$environment',journey='prometheus'}[7d]) > 0)",
     "legendFormat": "SLO Target 90%"
    }
   ]
  },
  {
   "title": "Error budget remaining over previous 7d",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(0.10000000000000001 - (1 - (sum(sum_over_time( slo_ok{service='monitoring',slo='SLI01',environment='$environment',journey='prometheus'}[7d] ))  / sum(sum_over_time(slo_sample{service='monitoring',slo='SLI01',environment='$environment',journey='prometheus'}[7d]) ) ) ) ) / 0.10000000000000001",
     "legendFormat": "Remaining Error Budget"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 0.5, "x": 14, "y": 0 } },
  {
   "type": "graph",
   "description": "the average of Average of prometheus scrape target status should be == 1.0",
   "gridPos": { "h": 1, "w": 9, "x": 14.5, "y": 0 },
   "targets": [
    {
     "expr": "sum_over_time ( slo_ok { service='monitoring',slo='SLI01',environment='$environment',journey='prometheus' } [ $__interval ] )\n/ \nsum_over_time ( slo_sample { service='monitoring',slo='SLI01',environment='$environment',journey='prometheus' } [ $__interval ] )\n",
     "legendFormat": "SLO OK"
    },
    {
     "expr": "1 - (\n  sum_over_time ( slo_ok { service='monitoring',slo='SLI01',environment='$environment',journey='prometheus' } [ $__interval ] )\n  / \n  sum_over_time ( slo_sample { service='monitoring',slo='SLI01',environment='$environment',journey='prometheus' } [ $__interval ] )\n)\n",
     "legendFormat": "SLO Fail"
    }
   ]
  },
  {
   "title": "Average of prometheus scrape target status",
   "type": "graph",
   "description": "* Sample interval is 1m \n",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(up{host=\"$environment\"}[1m])) / sum(count_over_time(up{host=\"$environment\"}[1m])) ",
     "legendFormat": "Average Average of prometheus scrape target status"
    }
   ]
  },
  {
   "title": "SLI02: Percentage of time prometheus scraping of Yace is fast enough",
   "type": "row"
  },
  {
   "title": "SLO Performance (7d)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(slo_ok{service='monitoring',slo='SLI02',environment='$environment',journey='prometheus'}[7d])) / sum(sum_over_time(slo_sample{service='monitoring',slo='SLI02',environment='$environment',journey='prometheus'}[7d]) > 0)",
     "legendFormat": "SLO Target 90%"
    }
   ]
  },
  {
   "title": "Error budget remaining over previous 7d",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(0.10000000000000001 - (1 - (sum(sum_over_time( slo_ok{service='monitoring',slo='SLI02',environment='$environment',journey='prometheus'}[7d] ))  / sum(sum_over_time(slo_sample{service='monitoring',slo='SLI02',environment='$environment',journey='prometheus'}[7d]) ) ) ) ) / 0.10000000000000001",
     "legendFormat": "Remaining Error Budget"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 0.5, "x": 14, "y": 0 } },
  {
   "type": "graph",
   "description": "the average of Average duration of Prometheus scrape of Yace should be < 15.0",
   "gridPos": { "h": 1, "w": 9, "x": 14.5, "y": 0 },
   "targets": [
    {
     "expr": "sum_over_time ( slo_ok { service='monitoring',slo='SLI02',environment='$environment',journey='prometheus' } [ $__interval ] )\n/ \nsum_over_time ( slo_sample { service='monitoring',slo='SLI02',environment='$environment',journey='prometheus' } [ $__interval ] )\n",
     "legendFormat": "SLO OK"
    },
    {
     "expr": "1 - (\n  sum_over_time ( slo_ok { service='monitoring',slo='SLI02',environment='$environment',journey='prometheus' } [ $__interval ] )\n  / \n  sum_over_time ( slo_sample { service='monitoring',slo='SLI02',environment='$environment',journey='prometheus' } [ $__interval ] )\n)\n",
     "legendFormat": "SLO Fail"
    }
   ]
  },
  {
   "title": "Average duration of Prometheus scrape of Yace",
   "type": "graph",
   "description": "* Sample interval is 1m \n",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(scrape_duration_seconds{job=\"yace\",host=\"$environment\"}[1m])) / sum(count_over_time(scrape_duration_seconds{job=\"yace\",host=\"$environment\"}[1m])) ",
     "legendFormat": "Average Average duration of Prometheus scrape of Yace"
    }
   ]
  }
 ]
}