"groups":
- "name": "flapi_prp1_recordingrules"
  "rules":
  - "expr": |
      sum(rate(http_server_requests_seconds_count{job=~".*/fetm-flapi-wb",host="prp1",status=~"4..|5.."}[5m]) or vector(0)) / sum(rate(http_server_requests_seconds_count{job=~".*/fetm-flapi-wb",host="prp1"}[5m]))
      < bool 0.10000000000000001
    "labels":
      "category": "Availability"
      "environment": "prp1"
      "journey": "writeback"
      "service": "flapi"
      "slo": "SLI01"
      "type": "http-errors"
    "record": "slo_ok"
  - "expr": |
      sum(rate(http_server_requests_seconds_count{job=~".*/fetm-flapi-wb",host="prp1",status=~"4..|5.."}[5m]) or vector(0)) / sum(rate(http_server_requests_seconds_count{job=~".*/fetm-flapi-wb",host="prp1"}[5m]))
      < bool Inf
    "labels":
      "category": "Availability"
      "environment": "prp1"
      "journey": "writeback"
      "service": "flapi"
      "slo": "SLI01"
      "type": "http-errors"
    "record": "slo_sample"
  - "expr": |
      (sum(sum_over_time(slo_ok{service='flapi',slo='SLI01',environment='prp1',journey='writeback'}[5m]) or vector(0)) / sum(sum_over_time(slo_sample{service='flapi',slo='SLI01',environment='prp1',journey='writeback'}[5m]) or vector(0)))
      >= 0
    "labels":
      "category": "Availability"
      "environment": "prp1"
      "journey": "writeback"
      "service": "flapi"
      "slo": "SLI01"
      "type": "http-errors"
    "record": "slo_percentage"
  - "expr": |
      (
        1 -
        (
          sum(sum_over_time(slo_ok{service='flapi',slo='SLI01',environment='prp1',journey='writeback'}[1d]))
          /
          ( sum(sum_over_time(slo_sample{service='flapi',slo='SLI01',environment='prp1',journey='writeback'}[1d])) > 0 )
        )
      ) / 0.10000 or vector (0)
    "labels":
      "environment": "prp1"
      "journey": "writeback"
      "service": "flapi"
      "slo": "SLI01"
    "record": "slo_burnrate:1d"
  - "expr": |
      (
        1 -
        (
          sum(sum_over_time(slo_ok{service='flapi',slo='SLI01',environment='prp1',journey='writeback'}[1h]))
          /
          ( sum(sum_over_time(slo_sample{service='flapi',slo='SLI01',environment='prp1',journey='writeback'}[1h])) > 0 )
        )
      ) / 0.10000 or vector (0)
    "labels":
      "environment": "prp1"
      "journey": "writeback"
      "service": "flapi"
      "slo": "SLI01"
    "record": "slo_burnrate:1h"
  - "expr": |
      (
        1 -
        (
          sum(sum_over_time(slo_ok{service='flapi',slo='SLI01',environment='prp1',journey='writeback'}[2h]))
          /
          ( sum(sum_over_time(slo_sample{service='flapi',slo='SLI01',environment='prp1',journey='writeback'}[2h])) > 0 )
        )
      ) / 0.10000 or vector (0)
    "labels":
      "environment": "prp1"
      "journey": "writeback"
      "service": "flapi"
      "slo": "SLI01"
    "record": "slo_burnrate:2h"
  - "expr": |
      (
        1 -
        (
          sum(sum_over_time(slo_ok{service='flapi',slo='SLI01',environment='prp1',journey='writeback'}[30m]))
          /
          ( sum(sum_over_time(slo_sample{service='flapi',slo='SLI01',environment='prp1',journey='writeback'}[30m])) > 0 )
        )
      ) / 0.10000 or vector (0)
    "labels":
      "environment": "prp1"
      "journey": "writeback"
      "service": "flapi"
      "slo": "SLI01"
    "record": "slo_burnrate:30m"
  - "expr": |
      (
        1 -
        (
          sum(sum_over_time(slo_ok{service='flapi',slo='SLI01',environment='prp1',journey='writeback'}[3d]))
          /
          ( sum(sum_over_time(slo_sample{service='flapi',slo='SLI01',environment='prp1',journey='writeback'}[3d])) > 0 )
        )
      ) / 0.10000 or vector (0)
    "labels":
      "environment": "prp1"
      "journey": "writeback"
      "service": "flapi"
      "slo": "SLI01"
    "record": "slo_burnrate:3d"
  - "expr": |
      (
        1 -
        (
          sum(sum_over_time(slo_ok{service='flapi',slo='SLI01',environment='prp1',journey='writeback'}[5m]))
          /
          ( sum(sum_over_time(slo_sample{service='flapi',slo='SLI01',environment='prp1',journey='writeback'}[5m])) > 0 )
        )
      ) / 0.10000 or vector (0)
    "labels":
      "environment": "prp1"
      "journey": "writeback"
      "service": "flapi"
      "slo": "SLI01"
    "record": "slo_burnrate:5m"
  - "expr": |
      (
        1 -
        (
          sum(sum_over_time(slo_ok{service='flapi',slo='SLI01',environment='prp1',journey='writeback'}[6h]))
          /
          ( sum(sum_over_time(slo_sample{service='flapi',slo='SLI01',environment='prp1',journey='writeback'}[6h])) > 0 )
        )
      ) / 0.10000 or vector (0)
    "labels":
      "environment": "prp1"
      "journey": "writeback"
      "service": "flapi"
      "slo": "SLI01"
    "record": "slo_burnrate:6h"
  - "expr": |
      histogram_quantile(0.95, (sum by (le) (rate(http_server_requests_seconds_bucket{job=~".*/fetm-flapi-wb",host="prp1"}[5m]))))
      < bool 0.75
    "labels":
      "category": "Latency"
      "environment": "prp1"
      "journey": "writeback"
      "service": "flapi"
      "slo": "SLI02"
      "type": "http-latency"
    "record": "slo_ok"
  - "expr": |
      histogram_quantile(0.95, (sum by (le) (rate(http_server_requests_seconds_bucket{job=~".*/fetm-flapi-wb",host="prp1"}[5m]))))
      < bool Inf
    "labels":
      "category": "Latency"
      "environment": "prp1"
      "journey": "writeback"
      "service": "flapi"
      "slo": "SLI02"
      "type": "http-latency"
    "record": "slo_sample"
  - "expr": |
      (sum(sum_over_time(slo_ok{service='flapi',slo='SLI02',environment='prp1',journey='writeback'}[5m]) or vector(0)) / sum(sum_over_time(slo_sample{service='flapi',slo='SLI02',environment='prp1',journey='writeback'}[5m]) or vector(0)))
      >= 0
    "labels":
      "category": "Latency"
      "environment": "prp1"
      "journey": "writeback"
      "service": "flapi"
      "slo": "SLI02"
      "type": "http-latency"
    "record": "slo_percentage"
  - "expr": |
      (
        1 -
        (
          sum(sum_over_time(slo_ok{service='flapi',slo='SLI02',environment='prp1',journey='writeback'}[1d]))
          /
          ( sum(sum_over_time(slo_sample{service='flapi',slo='SLI02',environment='prp1',journey='writeback'}[1d])) > 0 )
        )
      ) / 0.10000 or vector (0)
    "labels":
      "environment": "prp1"
      "journey": "writeback"
      "service": "flapi"
      "slo": "SLI02"
    "record": "slo_burnrate:1d"
  - "expr": |
      (
        1 -
        (
          sum(sum_over_time(slo_ok{service='flapi',slo='SLI02',environment='prp1',journey='writeback'}[1h]))
          /
          ( sum(sum_over_time(slo_sample{service='flapi',slo='SLI02',environment='prp1',journey='writeback'}[1h])) > 0 )
        )
      ) / 0.10000 or vector (0)
    "labels":
      "environment": "prp1"
      "journey": "writeback"
      "service": "flapi"
      "slo": "SLI02"
    "record": "slo_burnrate:1h"
  - "expr": |
      (
        1 -
        (
          sum(sum_over_time(slo_ok{service='flapi',slo='SLI02',environment='prp1',journey='writeback'}[2h]))
          /
          ( sum(sum_over_time(slo_sample{service='flapi',slo='SLI02',environment='prp1',journey='writeback'}[2h])) > 0 )
        )
      ) / 0.10000 or vector (0)
    "labels":
      "environment": "prp1"
      "journey": "writeback"
      "service": "flapi"
      "slo": "SLI02"
    "record": "slo_burnrate:2h"
  - "expr": |
      (
        1 -
        (
          sum(sum_over_time(slo_ok{service='flapi',slo='SLI02',environment='prp1',journey='writeback'}[30m]))
          /
          ( sum(sum_over_time(slo_sample{service='flapi',slo='SLI02',environment='prp1',journey='writeback'}[30m])) > 0 )
        )
      ) / 0.10000 or vector (0)
    "labels":
      "environment": "prp1"
      "journey": "writeback"
      "service": "flapi"
      "slo": "SLI02"
    "record": "slo_burnrate:30m"
  - "expr": |
      (
        1 -
        (
          sum(sum_over_time(slo_ok{service='flapi',slo='SLI02',environment='prp1',journey='writeback'}[3d]))
          /
          ( sum(sum_over_time(slo_sample{service='flapi',slo='SLI02',environment='prp1',journey='writeback'}[3d])) > 0 )
        )
      ) / 0.10000 or vector (0)
    "labels":
      "environment": "prp1"
      "journey": "writeback"
      "service": "flapi"
      "slo": "SLI02"
    "record": "slo_burnrate:3d"
  - "expr": |
      (
        1 -
        (
          sum(sum_over_time(slo_ok{service='flapi',slo='SLI02',environment='prp1',journey='writeback'}[5m]))
          /
          ( sum(sum_over_time(slo_sample{service='flapi',slo='SLI02',environment='prp1',journey='writeback'}[5m])) > 0 )
        )
      ) / 0.10000 or vector (0)
    "labels":
      "environment": "prp1"
      "journey": "writeback"
      "service": "flapi"
      "slo": "SLI02"
    "record": "slo_burnrate:5m"
  - "expr": |
      (
        1 -
        (
          sum(sum_over_time(slo_ok{service='flapi',slo='SLI02',environment='prp1',journey='writeback'}[6h]))
          /
          ( sum(sum_over_time(slo_sample{service='flapi',slo='SLI02',environment='prp1',journey='writeback'}[6h])) > 0 )
        )
      ) / 0.10000 or vector (0)
    "labels":
      "environment": "prp1"
      "journey": "writeback"
      "service": "flapi"
      "slo": "SLI02"
    "record": "slo_burnrate:6h"
