# The root route on which each incoming alert enters.
route:
    receiver: health_alerts_prod_monitoring
    # The labels by which incoming alerts are grouped together. For example,
    # multiple alerts coming in for cluster=A and alertname=LatencyHigh would
    # be batched into a single group.
    group_by: ['alertname', 'environment', 'service', 'journey']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 1h

# A list of notification receivers.
receivers:
    - name: health_alerts_prod_monitoring
      slack_configs:
          - send_resolved: true
            api_url: https://hooks.slack.com/services/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
            channel: '#sas-monitoring-test'
            title: "MGMT - HEALTH - {{ .CommonLabels.service }} - {{ .CommonLabels.severity}} - {{ .CommonLabels.short_description }}"
            text: >-
                Alert from EBSA-Monitoring
                {{ with index .Alerts 0 -}}
                  :chart_with_upwards_trend: *<{{ .Annotations.dashboardurl }}|Dashboard>*   :no_bell: *<{{ .Annotations.silenceurl }}|Silence>*
                  {{- if .Annotations.runbookurl }}   :notebook: *<{{ .Annotations.runbookurl }}|Runbook>*{{ end }}
                {{ end }}
                {{ range .Alerts -}}
                {{ range .Labels.SortedPairs -}} 
                  *{{ .Name }}:* {{ .Value }}
                {{ end }}
                *time_of_event:* {{ .StartsAt }}
                {{ end }}