{
 "title": "monitoring-prometheus-journey-view",
 "tags": [
  "monitoring",
  "mac-version: 65-migrate-monitoring-as-code-base-files-to-github",
  "prometheus",
  "journey-view"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "error_budget_span", "label": "Error Budget Display", "query": "10m,1h,1d,7d,21d,30d,90d" },
   { "name": "environment", "label": "Environment", "query": "label_values(environment)" }
  ]
 },
 "panels": [
  {
   "title": "SLI01: all prometheus scrape targets are available",
   "type": "row"
  },
  {
   "title": "SLO Performance (7d)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((sli_value{service='monitoring', slo='SLI01', environment='$environment',\n          journey='prometheus'}\n== bool 1)[7d:1m]))\n/\nsum(sum_over_time((sli_value{service='monitoring', slo='SLI01', environment='$environment',\n          journey='prometheus'}\n< bool Inf)[7d:1m]) > 0)\n",
     "legendFormat": "SLO Target 90.0 %"
    }
   ]
  },
  {
   "title": "Error budget remaining over previous 7d",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(0.10000000000000001 - (1 - (sum(sum_over_time((sli_value{service='monitoring', slo='SLI01', environment='$environment',\n          journey='prometheus'}\n== bool 1)[7d:1m]))\n/\nsum(sum_over_time((sli_value{service='monitoring', slo='SLI01', environment='$environment',\n          journey='prometheus'}\n< bool Inf)[7d:1m])))))\n/\n0.10000000000000001\n",
     "legendFormat": "Remaining Error Budget"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 0.5, "x": 14, "y": 0 } },
  {
   "type": "graph",
   "description": "the average of Average of prometheus scrape target status should be == 1.0",
   "gridPos": { "h": 1, "w": 9, "x": 14.5, "y": 0 },
   "targets": [
    {
     "expr": "sum_over_time((sli_value{service='monitoring', slo='SLI01', environment='$environment',\n          journey='prometheus'} == bool 1)[$__interval:1m])\n/ \nsum_over_time((sli_value{service='monitoring', slo='SLI01', environment='$environment',\n          journey='prometheus'} < bool Inf)[$__interval:1m])\n",
     "legendFormat": "SLO OK"
    },
    {
     "expr": "1 - (\n  sum_over_time((sli_value{service='monitoring', slo='SLI01', environment='$environment',\n          journey='prometheus'} == bool 1)[$__interval:1m])\n  / \n  sum_over_time((sli_value{service='monitoring', slo='SLI01', environment='$environment',\n          journey='prometheus'} < bool Inf)[$__interval:1m])\n)\n",
     "legendFormat": "SLO Fail"
    }
   ]
  },
  {
   "title": "Average of prometheus scrape target status",
   "type": "graph",
   "description": "* Sample interval is 1m \n",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(up{namespace=~\"$environment\"}[1m])) / \n        sum(count_over_time(up{namespace=~\"$environment\"}[1m]))",
     "legendFormat": "Average Average of prometheus scrape target status"
    }
   ]
  },
  {
   "title": "SLI02: prometheus scraping of Yace is fast enough",
   "type": "row"
  },
  {
   "title": "SLO Performance (7d)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((sli_value{service='monitoring', slo='SLI02', environment='$environment',\n          journey='prometheus'}\n< bool 15)[7d:1m]))\n/\nsum(sum_over_time((sli_value{service='monitoring', slo='SLI02', environment='$environment',\n          journey='prometheus'}\n< bool Inf)[7d:1m]) > 0)\n",
     "legendFormat": "SLO Target 90.0 %"
    }
   ]
  },
  {
   "title": "Error budget remaining over previous 7d",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(0.10000000000000001 - (1 - (sum(sum_over_time((sli_value{service='monitoring', slo='SLI02', environment='$environment',\n          journey='prometheus'}\n< bool 15)[7d:1m]))\n/\nsum(sum_over_time((sli_value{service='monitoring', slo='SLI02', environment='$environment',\n          journey='prometheus'}\n< bool Inf)[7d:1m])))))\n/\n0.10000000000000001\n",
     "legendFormat": "Remaining Error Budget"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 0.5, "x": 14, "y": 0 } },
  {
   "type": "graph",
   "description": "the average of Average duration of Prometheus scrape of Yace should be < 15.0",
   "gridPos": { "h": 1, "w": 9, "x": 14.5, "y": 0 },
   "targets": [
    {
     "expr": "sum_over_time((sli_value{service='monitoring', slo='SLI02', environment='$environment',\n          journey='prometheus'} < bool 15)[$__interval:1m])\n/ \nsum_over_time((sli_value{service='monitoring', slo='SLI02', environment='$environment',\n          journey='prometheus'} < bool Inf)[$__interval:1m])\n",
     "legendFormat": "SLO OK"
    },
    {
     "expr": "1 - (\n  sum_over_time((sli_value{service='monitoring', slo='SLI02', environment='$environment',\n          journey='prometheus'} < bool 15)[$__interval:1m])\n  / \n  sum_over_time((sli_value{service='monitoring', slo='SLI02', environment='$environment',\n          journey='prometheus'} < bool Inf)[$__interval:1m])\n)\n",
     "legendFormat": "SLO Fail"
    }
   ]
  },
  {
   "title": "Average duration of Prometheus scrape of Yace",
   "type": "graph",
   "description": "* Sample interval is 1m \n",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(scrape_duration_seconds{job=~\"yace\",namespace=~\"$environment\"}[1m])) / \n        sum(count_over_time(scrape_duration_seconds{job=~\"yace\",namespace=~\"$environment\"}[1m]))",
     "legendFormat": "Average Average duration of Prometheus scrape of Yace"
    }
   ]
  }
 ]
}