{
 "title": "monitoring-thanos-detail-view",
 "tags": [
  "monitoring",
  "mac-version: 65-migrate-monitoring-as-code-base-files-to-github",
  "thanos",
  "detail-view"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "environment", "label": "Environment", "query": "label_values(environment)" },
   {
    "name": "inbound_code",
    "label": "Inbound Code",
    "query": "label_values({__name__=~\"http_request_duration_seconds_bucket|http_request_duration_seconds_count|http_request_duration_seconds_sum|http_requests_total|thanos_compact_group_compactions_failures_total|thanos_compact_group_compactions_total\", namespace=~\"$environment|\", job=~\"monitoring-thanos-compact.*|thanos-query|\"}, code)"
   },
   {
    "name": "inbound_handler",
    "label": "Inbound Handler",
    "query": "label_values({__name__=~\"http_request_duration_seconds_bucket|http_request_duration_seconds_count|http_request_duration_seconds_sum|http_requests_total|thanos_compact_group_compactions_failures_total|thanos_compact_group_compactions_total\", namespace=~\"$environment|\", job=~\"monitoring-thanos-compact.*|thanos-query|\"}, handler)"
   },
   { "name": "inbound_latency_percentile", "label": "Inbound Latency Percentile", "query": "50,80,90,95,99" }
  ]
 },
 "panels": [
  {
   "title": "Inbound HTTP Requests Availability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24 }
  },
  {
   "title": "Availability - requests per second by response code",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate({__name__=~\"http_requests_total\", namespace=~\"$environment|\", code=~\"$inbound_code|\", job=~\"monitoring-thanos-compact.*|thanos-query|\", handler=~\"$inbound_handler|\"}[$__rate_interval]))\n",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Availability - requests per second by path",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (handler) (rate({__name__=~\"http_requests_total\", namespace=~\"$environment|\", code=~\"$inbound_code|\", job=~\"monitoring-thanos-compact.*|thanos-query|\", handler=~\"$inbound_handler|\"}[$__rate_interval]))\n",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  { "title": "Inbound HTTP Requests Latency", "type": "row", "gridPos": { "h": 1, "w": 24 } },
  {
   "title": "Latency - heatmap for request latency",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12 },
   "targets": [
    {
     "expr": "sum by (le) (increase({__name__=~\"http_request_duration_seconds_bucket\", namespace=~\"$environment|\", code=~\"$inbound_code|\", job=~\"monitoring-thanos-compact.*|thanos-query|\", handler=~\"$inbound_handler|\"}[$__rate_interval]))\n",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Latency - requests per selected latency percentile",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($inbound_latency_percentile/100, (sum by (le) (rate({__name__=~\"http_request_duration_seconds_bucket\",\nnamespace=~\"$environment|\", code=~\"$inbound_code|\", job=~\"monitoring-thanos-compact.*|thanos-query|\", handler=~\"$inbound_handler|\"}[$__rate_interval]))))\n",
     "legendFormat": "Selected Percentile Latency"
    }
   ]
  }
 ]
}