name: ci

on: [push,pull_request]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./monitoring-as-code
          file: ./monitoring-as-code/Dockerfile
          push: true
          tags: |
            ghcr.io/ho-cto/humayunapp:latest
            ghcr.io/ho-cto/humayunapp:1.0.0


