name: docker-build-push

#on: [push,pull_request]

on:
  push:
    branches:
      - '94-container-image-build-and-push'
    tags:
      - 'v*'
  pull_request:
    branches:
      - '94-container-image-build-and-push'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

        #Checks-out our repository under $GITHUB_WORKSPACE, so our workflow can access it.    
      - name: Checkout 
        uses: actions/checkout@v2

        #Logs into Github registry     
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

        #Will setup Docker Buildx to create the builder instance using a BuildKit container under the hood.     
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/ho-cto/sre-monitoring-as-code
          tags: |
            # minimal (short sha)
            type=sha




      - name: Build and push
        uses: docker/build-push-action@v3.1.0
        with:
          context: ./monitoring-as-code
          file: ./monitoring-as-code/Dockerfile
          push: true
#          tags: ghcr.io/ho-cto/sre-monitoring-as-code:test
#          tags: ${{ steps.meta.outputs.tags }}
          tags: ${{ steps.meta.outputs.sha }}
          labels: ${{ steps.meta.outputs.sha }}



