name: 'Feature'

on:
  pull_request:
    types: [ labeled, opened, reopened, synchronize ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  REPO_NAME: ${{ github.event.repository.name }}
  PROMTOOL_IMAGE_NAME: sre-promtool
  PROMTOOL_VERSION: 2.38.0
  USER: ho-cto

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Hadolint Dockerfile
        uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: ./monitoring-as-code/Dockerfile
      - name: Jsonnet format check
        run: sh ${{ github.workspace }}/monitoring-as-code/fmt.sh && git diff --exit-code --color
      - name: Jsonnet lint check
        run: sh ${{ github.workspace }}/monitoring-as-code/lint.sh

  container-image:
    uses: ./.github/workflows/build-container-image.yml
    with:
      imageRegistry: ghcr.io
      imageName: ${{ github.repository }}
      imageBuildContext: ./monitoring-as-code
      repositoryName: ${{ github.event.repository.name }}
      promtoolImageName: sre-promtool
      promtoolVersion: 2.38.0
      user: ho-cto
    secrets: inherit

  container-image-push:
    needs: container-image
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Download artifact
        uses: actions/download-artifact@v3.0.1
        with:
          name: ${{ env.REPO_NAME }}
          path: /tmp
      - name: Load Docker image
        run: |
          docker load --input /tmp/${{ env.REPO_NAME }}.tar
          echo "IMAGE_TAG=$(docker image ls --format '{{.Repository}}:{{.Tag}}' | grep sre-monitoring-as-code)" >> $GITHUB_ENV
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image to GitHub Container Registry
        run: docker push ${{ env.IMAGE_TAG }}