name: 'docker-fmt-lint'

on:
  workflow_dispatch

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: sre-fmt-lint
  USER: ho-cto

jobs:
  publish-jsonnet-dev-tool:
    name: 'Build fmt lint tool'
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

        #Logs into Github registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container
        run: docker build -t ${{ env.REGISTRY }}/${{ env.USER }}/${{ env.IMAGE_NAME }} ${GITHUB_WORKSPACE}/monitoring-as-code/tools/jsonnet-dev-tool

      - name: Push image to GitHub Container Registry
        run: docker push ${{ env.REGISTRY }}/${{ env.USER }}/${{ env.IMAGE_NAME }}