name: jsonnet formatter

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: formatter jsonnet
      uses: kakkoyun/action-jsonnetfmt@master
