name: secret-scan

on: [push,pull_request]

jobs:
  secret-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: gitleaks-action
        uses: gitleaks/gitleaks-action@v1.6.0
        with:
          config-path: security/.gitleaks.toml

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.16.3
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
