name: secret-scan

on: [push,pull_request]

jobs:
  secret-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: gitleaks-action
        uses: gitleaks/gitleaks-action@v2.0.6
        with:
          config-path: security/.gitleaks.toml