name: 'Snyk iac scan'

on:
  push:
    branches:
      - 163-code-scanning-for-iac-files

  schedule:
    - cron: '0 */2 * * *'  

jobs:

  iac_results:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check configuration files for security issues
        continue-on-error: true
        uses: snyk/actions/iac@0.3.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: .
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
          name: Infrastructure as Code Snyk Results
