name: 'Snyk Code Analysis'

on:
  push:
    branches:
      - 163-code-scanning-for-iac-files
  schedule:
    - cron: '0 */2 * * *'  

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: snyk/actions/setup@0.3.0
      - name: Snyk Code Test
        continue-on-error: true
        run: snyk code test --sarif > snyk.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Upload results to Github Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
 
