name: 'Docker Build Tag'
on:
  workflow_call:
    inputs:
      images:
        required: true
        type: string
  push,pull_request:


jobs:
  publish:
    name: 'Main Publish'
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'skip-release') == false
    steps:
      - name: Parse the SemVer label
        id: label
        uses: UKHomeOffice/match-label-action@v1
        with:
          labels: minor,major,patch
          mode: singular

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Calculate SemVer increment
        id: increment
        uses: UKHomeOffice/semver-tag-action@v2
        with:
          increment: ${{ steps.label.outputs.matchedLabels }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_use_head_tag: ${{ github.base_ref == 'main' }}
          dry_run: true

      - name: Calculate metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ inputs.images }}
          tags: |
            type=raw,value=${{steps.increment.outputs.version}}
            type=raw,value=latest,enable=${{ github.base_ref == 'main' }}
    
      - name: Build container
        uses: docker/build-push-action@v3
        with:
          context: ./monitoring-as-code
          file: ./monitoring-as-code/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            PACKAGE_TOKEN=${{secrets.GITHUB_TOKEN}}
      
      - name: Tag repository with SemVer
        uses: UKHomeOffice/semver-tag-action@v2
        with:
          tag: ${{steps.increment.outputs.version}}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_use_head_tag: ${{ github.base_ref == 'main' }}
